from mastodon import Mastodon
from dotenv import load_dotenv
import os, random, re

load_dotenv()

mastodon = Mastodon(
    client_id=os.getenv("client_key"),
    client_secret=os.getenv("client_secret"),
    access_token=os.getenv("access_token"),
    api_base_url="https://mastodon.social",
)


movieCriteria = [
    ["feels the ", "MOST", "LEAST", " likely to pass the Bechdel test"],
    ["feels the ", "MOST", "LEAST", " like a cash grab"],
    ["feels the ", "MOST", "LEAST", " like a ripoff of a better film"],
    ["feels the ", "MOST", "LEAST", " made-for-tv"],
    ["feels the ", "MOST", "LEAST", " outdated"],
    ["had the ", "MOST", "LEAST", " wasted potential"],
    ["has the ", "BIGGEST", "SMALLEST", " baddie"],
    ["has the ", "MOST EXPENSIVE", "CHEAPEST", " looking sets"],
    ["has the ", "MOST", "FEWEST", " deaths"],
    ["has the ", "MOST", "FEWEST", " famous actors"],
    ["has the ", "MOST", "FEWEST", " frogs"],
    ["has the ", "MOST", "FEWEST", " little guys"],
    ["has the ", "MOST", "FEWEST", " vegetarians"],
    ["has the ", "MOST", "LEAST", " B.D.E."],
    ["has the ", "MOST", "LEAST", " big dinosaur energy"],
    ["has the ", "MOST", "LEAST", " 'David Bowie' energy"],
    ["has the ", "MOST", "LEAST", " 'Vincent Price' energy"],
    ["has the ", "MOST", "LEAST", " 'castle' energy"],
    ["has the ", "MOST", "LEAST", " 'industrial' energy"],
    ["has the ", "MOST", "LEAST", " action"],
    ["has the ", "MOST", "LEAST", " amount of effort"],
    ["has the ", "MOST", "LEAST", " blood"],
    ["has the ", "MOST", "LEAST", " cheese"],
    ["has the ", "MOST", "LEAST", " coffee served"],
    ["has the ", "MOST", "LEAST", " competent hero"],
    ["has the ", "MOST", "LEAST", " consistent monster size"],
    ["has the ", "MOST", "LEAST", " conventional weapon"],
    ["has the ", "MOST", "LEAST", " convincing-looking monster"],
    ["has the ", "MOST", "LEAST", " dangerous monster"],
    ["has the ", "MOST", "LEAST", " destruction"],
    ["has the ", "MOST", "LEAST", " effective military or police"],
    ["has the ", "MOST", "LEAST", " fur"],
    ["has the ", "MOST", "LEAST", " growth"],
    ["has the ", "MOST", "LEAST", " monster screen time"],
    ["has the ", "MOST", "LEAST", " 'bird' energy"],
    ["has the ", "MOST", "LEAST", " 'bug' energy"],
    ["has the ", "MOST", "LEAST", " 'college' energy"],
    ["has the ", "MOST", "LEAST", " 'colonial' energy"],
    ["has the ", "MOST", "LEAST", " 'dad' energy"],
    ["has the ", "MOST", "LEAST", " 'Damsel in Distress' energy"],
    ["has the ", "MOST", "LEAST", " 'dragon' energy"],
    ["has the ", "MOST", "LEAST", " 'Earth' energy"],
    ["has the ", "MOST", "LEAST", " 'Florida' energy"],
    ["has the ", "MOST", "LEAST", " 'fish' energy"],
    ["has the ", "MOST", "LEAST", " 'flying' energy"],
    ["has the ", "MOST", "LEAST", " 'horse girl' energy "],
    ["has the ", "MOST", "LEAST", " 'Mad Scientist' energy"],
    ["has the ", "MOST", "LEAST", " 'plant' energy"],
    ["has the ", "MOST", "LEAST", " 'psychic' energy"],
    ["has the ", "MOST", "LEAST", " 'reptile' energy"],
    ["has the ", "MOST", "LEAST", " 'soccer mom' energy"],
    ["has the ", "MOST", "LEAST", " 'water' energy"],
    ["has the ", "MOST", "LEAST", " 'wind' energy"],
    ["has the ", "MOST", "LEAST", " abrupt ending"],
    ["has the ", "MOST", "LEAST", " aggressive Male Gaze"],
    ["has the ", "MOST", "LEAST", " annoying dialogue"],
    ["has the ", "MOST", "LEAST", " awkwardly-moving monster"],
    ["has the ", "MOST", "LEAST", " beach vibes"],
    ["has the ", "MOST", "LEAST", " boring filler scenes"],
    ["has the ", "MOST", "LEAST", " cartoonish-looking monster"],
    ["has the ", "MOST", "LEAST", " chewed scenery"],
    ["has the ", "MOST", "LEAST", " confusing geography"],
    ["has the ", "MOST", "LEAST", " confusing monster rules"],
    ["has the ", "MOST", "LEAST", " confusing plot"],
    ["has the ", "MOST", "LEAST", " crashes"],
    ["has the ", "MOST", "LEAST", " fake rocks"],
    ["has the ", "MOST", "LEAST", " fighting"],
    ["has the ", "MOST", "LEAST", " fire"],
    ["has the ", "MOST", "LEAST", " growth"],
    ["has the ", "MOST", "LEAST", " heart"],
    ["has the ", "MOST", "LEAST", " main character energy"],
    ["has the ", "MOST", "LEAST", " main character plot armor"],
    ["has the ", "MOST", "LEAST", " NASCAR energy"],
    ["has the ", "MOST", "LEAST", " nonsensical science"],
    ["has the ", "MOST", "LEAST", " plot holes"],
    ["has the ", "MOST", "LEAST", " rizz"],
    ["has the ", "MOST", "LEAST", " sandals"],
    ["has the ", "MOST", "LEAST", " toxic masculinity"],
    ["has the ", "MOST", "LEAST", " toxic vibe"],
    ["has the ", "MOST", "LEAST", " unnecessary scenes"],
    ["has the ", "MOST", "LEAST", " unnecessary slow-motion"],
    ["has the ", "MOST", "LEAST", " wood"],
    ["has the ", "FASTEST", "SLOWEST", " monster"],
    ["has the ", "BIGGEST", "SMALLEST", " baddie"],
    ["has the ", "STURDIEST", "FLIMSIEST", " looking sets"],
    ["has the ", "BEST", "WORST", " acting"],
    ["has the ", "BEST", "WORST", " characters"],
    ["has the ", "BEST", "WORST", " cinematography"],
    ["has the ", "BEST", "WORST", " costume and production design"],
    ["has the ", "BEST", "WORST", " ending"],
    ["has the ", "BEST", "WORST", " hero"],
    ["has the ", "BEST", "WORST", " monster/creature design"],
    ["has the ", "BEST", "WORST", " music and sound design"],
    ["has the ", "BEST", "WORST", " night scenes"],
    ["has the ", "BEST", "WORST", " plot twist"],
    ["has the ", "BEST", "WORST", " smell"],
    ["has the ", "BEST", "WORST", " story/script"],
    ["has the ", "BEST", "WORST", " tech"],
    ["has the ", "BEST", "WORST", " title"],
    ["has the ", "BEST", "WORST", " visual effects/CGI"],
    ["has the ", "BEST", "WORST", " weapons"],
    ["is the ", "BIGGEST", "SMALLEST", " disaster"],
    ["is the ", "MOST", "LEAST", " beefy"],
    ["is the ", "MOST", "LEAST", " chill"],
    ["is the ", "MOST", "LEAST", " complex"],
    ["is the ", "MOST", "LEAST", " dark"],
    ["is the ", "MOST", "LEAST", " David Lynch-esque"],
    ["is the ", "MOST", "LEAST", " Devil Girl From Mars-esque"],
    ["is the ", "MOST", "LEAST", " Dracula-esque"],
    ["is the ", "MOST", "LEAST", " dramatic"],
    ["is the ", "MOST", "LEAST", " epic"],
    ["is the ", "MOST", "LEAST", " erotic"],
    ["is the ", "MOST", "LEAST", " experimental"],
    ["is the ", "MOST", "LEAST", " Frankenstein-esque"],
    ["is the ", "MOST", "LEAST", " fun"],
    ["is the ", "MOST", "LEAST", " funky"],
    ["is the ", "MOST", "LEAST", " funny"],
    ["is the ", "MOST", "LEAST", " Godzilla-esque"],
    ["is the ", "MOST", "LEAST", " interesting"],
    ["is the ", "MOST", "LEAST", " kaiju-esque"],
    ["is the ", "MOST", "LEAST", " likely to become a cult classic"],
    ["is the ", "MOST", "LEAST", " memorable"],
    ["is the ", "MOST", "LEAST", " original"],
    ["is the ", "MOST", "LEAST", " patriotic"],
    ["is the ", "MOST", "LEAST", " powerful"],
    ["is the ", "MOST", "LEAST", " professional"],
    ["is the ", "MOST", "LEAST", " raucous"],
    ["is the ", "MOST", "LEAST", " rewatchable"],
        ["is the ", "MOST", "LEAST", " Roger Corman-esque"],
    ["is the ", "MOST", "LEAST", " scary"],
    ["is the ", "MOST", "LEAST", " serious"],
    ["is the ", "MOST", "LEAST", " Star Trek-esque"],
    ["is the ", "MOST", "LEAST", " Star Wars-esque"],
    ["is the ", "MOST", "LEAST", " thought-provoking"],
    ["is the ", "MOST", "LEAST", " Titanic-esque"],
    ["is the ", "MOST", "LEAST", " Twilight Zone-esque"],
    ["is the ", "MOST", "LEAST", " violent"],
    ["is the ", "MOST", "LEAST", " acidic"],
    ["is the ", "MOST", "LEAST", " adult"],
    ["is the ", "MOST", "LEAST", " American"],
    ["is the ", "MOST", "LEAST", " angsty"],
    ["is the ", "MOST", "LEAST", " annoying"],
    ["is the ", "MOST", "LEAST", " athletic"],
    ["is the ", "MOST", "LEAST", " camp"],
    ["is the ", "MOST", "LEAST", " cat-like"],
    ["is the ", "MOST", "LEAST", " cheap"],
    ["is the ", "MOST", "LEAST", " cheesy"],
    ["is the ", "MOST", "LEAST", " childish"],
    ["is the ", "MOST", "LEAST", " conservative"],
    ["is the ", "MOST", "LEAST", " cringe"],
    ["is the ", "MOST", "LEAST", " cryptic"],
    ["is the ", "MOST", "LEAST", " cursed"],
    ["is the ", "MOST", "LEAST", " destructive"],
    ["is the ", "MOST", "LEAST", " dim"],
    ["is the ", "MOST", "LEAST", " disappointing"],
    ["is the ", "MOST", "LEAST", " dreamlike"],
    ["is the ", "MOST", "LEAST", " dry"],
    ["is the ", "MOST", "LEAST", " dusty"],
    ["is the ", "MOST", "LEAST", " dystopian"],
    ["is the ", "MOST", "LEAST", " electric"],
    ["is the ", "MOST", "LEAST", " embarrassing"],
    ["is the ", "MOST", "LEAST", " fake"],
    ["is the ", "MOST", "LEAST", " fictional"],
    ["is the ", "MOST", "LEAST", " forbidden"],
    ["is the ", "MOST", "LEAST", " futuristic"],
    ["is the ", "MOST", "LEAST", " gothic"],
    ["is the ", "MOST", "LEAST", " graphic"],
    ["is the ", "MOST", "LEAST", " greasy"],
    ["is the ", "MOST", "LEAST", " hairy"],
    ["is the ", "MOST", "LEAST", " haunted"],
    ["is the ", "MOST", "LEAST", " hideous"],
    ["is the ", "MOST", "LEAST", " icy"],
    ["is the ", "MOST", "LEAST", " inspiring"],
    ["is the ", "MOST", "LEAST", " Jaws-esque"],
    ["is the ", "MOST", "LEAST", " juicy"],
    ["is the ", "MOST", "LEAST", " lazy"],
    ["is the ", "MOST", "LEAST", " liberal"],
    ["is the ", "MOST", "LEAST", " minimalist"],
    ["is the ", "MOST", "LEAST", " moist"],
    ["is the ", "MOST", "LEAST", " monsterous"],
    ["is the ", "MOST", "LEAST", " mouth-watering"],
    ["is the ", "MOST", "LEAST", " muscular"],
    ["is the ", "MOST", "LEAST", " nerdy"],
    ["is the ", "MOST", "LEAST", " noisy"],
    ["is the ", "MOST", "LEAST", " offensive"],
    ["is the ", "MOST", "LEAST", " pointless"],
    ["is the ", "MOST", "LEAST", " poisonous"],
    ["is the ", "MOST", "LEAST", " predictable"],
    ["is the ", "MOST", "LEAST", " pretentious"],
    ["is the ", "MOST", "LEAST", " psychedelic"],
    ["is the ", "MOST", "LEAST", " radioactive"],
    ["is the ", "MOST", "LEAST", " religious"],
    ["is the ", "MOST", "LEAST", " salty"],
    ["is the ", "MOST", "LEAST", " Satanic"],
    ["is the ", "MOST", "LEAST", " sharp"],
    ["is the ", "MOST", "LEAST", " sleazy"],
    ["is the ", "MOST", "LEAST", " slimy"],
    ["is the ", "MOST", "LEAST", " small"],
    ["is the ", "MOST", "LEAST", " spacey"],
    ["is the ", "MOST", "LEAST", " spicy"],
    ["is the ", "MOST", "LEAST", " sticky"],
    ["is the ", "MOST", "LEAST", " stiff"],
    ["is the ", "MOST", "LEAST", " swampy"],
    ["is the ", "MOST", "LEAST", " teen"],
    ["is the ", "MOST", "LEAST", " thirsty"],
    ["is the ", "MOST", "LEAST", " tone deaf"],
    ["is the ", "MOST", "LEAST", " tough"],
    ["is the ", "MOST", "LEAST", " transparent"],
    ["is the ", "MOST", "LEAST", " trashy"],
    ["is the ", "MOST", "LEAST", " tropical"],
    ["is the ", "MOST", "LEAST", " urban"],
    ["is the ", "MOST", "LEAST", " suburban"],
    ["is the ", "MOST", "LEAST", " punk"],
    ["is the ", "MOST", "LEAST", " jazzy"],
    ["is the ", "MOST", "LEAST", " rural"],
    ["is the ", "MOST", "LEAST", " underground"],
    ["is the ", "MOST", "LEAST", " unnecessary"],
    ["is the ", "MOST", "LEAST", " wacky"],
    ["is the ", "MOST", "LEAST", " wrong"],
    ["is the ", "MOST", "LEAST", " rhythmic"],
    ["is the ", "MOST", "LEAST", " dynamic"],
    ["is the ", "MOST", "LEAST", " energetic"],
    ["would make the ", "BEST", "WORST", " video game"],
    ["is the ", "MOST", "LEAST", " likely to get big-budget remake"],
    ["would be the ", "MOST", "LEAST", " fun to watch on a first date"],
    ["would be the ", "MOST", "LEAST", " awkward to watch with your parents"],
    ["would be the ", "MOST", "LEAST", " likely to give a child nightmares"],
    ["would be the ", "MOST", "LEAST", " fun to watch while intoxicated"],
    ["would be the ", "MOST", "LEAST", " appropriate to play at a wedding"],
    ["would be the ", "MOST", "LEAST", " appropriate to play at a funeral"],
    ["would be the ", "MOST", "LEAST", " stressful to live through in real life"],
    ["is the ", "MOST", "LEAST", " likely to be shown in a science class"],
    ["would have the ", "BEST", "WORST", " themed restaurant"],
    ["would have the ", "BEST", "WORST", " escape room theme"],
    ["would have the ", "BEST", "WORST", " fan fiction"],
    ["would have the ", "BEST", "WORST", " action figures"],
    ["would make the ", "BEST", "WORST", " Saturday morning cartoon"],
    ["would make the ", "BEST", "WORST", " Broadway musical"],
    ["would make the ", "BEST", "WORST", " roller coaster"],
    ["would make the ", "BEST", "WORST", " children's bedtime story"],
    ["would have the ", "BEST", "WORST", " breakfast cereal"],
    ["would be the ", "BEST", "WORST", " to have as a lower-back tattoo"],
    ["would be the ", "BEST", "WORST", " to have as a permanent nickname"],
    ["would be the ", "BEST", "WORST", " to be trapped inside for 24 hours"],
    ["has the ", "MOST", "LEAST", " product placement"],
    ["is the ", "MOST", "LEAST", " likely to make someone quezy"],
    ["is the ", "MOST", "LEAST", " likely to make someone cry"],
    ["is the ", "MOST", "LEAST", " likely to contain a subliminal message"],
    ["is the ", "MOST", "LEAST", " likely to be a front for a CIA experiment"],
    ["is the ", "MOST", "LEAST", " likely to be the leader of a high school club"],
    ["is the ", "MOST", "LEAST", " likely to have a theme song that actually slaps"],
    ["is the ", "MOST", "LEAST", " likely to steal your wallet"],
    ["is the ", "MOST", "LEAST", " likely to ghost you after the first date"],
    ["is the ", "MOST", "LEAST", " likely to be a pyramid scheme"],
    ["is the ", "MOST", "LEAST", " likely to be banned from a public library"],
    ["is the ", "MOST", "LEAST", " likely to become a cult classic"],
    ["is the ", "MOST", "LEAST", " likely to feature a Yeti's nipple"],
    ["is the ", "MOST", "LEAST", " likely to feature a stop motion creature"],
    ["is the ", "MOST", "LEAST", " likely to use the term 'glaive' incorrectly"],
    ["has the ", "MOST", "LEAST", " 'Dungeons and Dragons' energy"],
    ["has the ", "MOST", "LEAST", " mountain energy"],
    ["is the ", "MOST", "LEAST", " beastly"],
    ["is the ", "MOST", "LEAST", " green"],
    ["is the ", "MOST", "LEAST", " organic"],
    ["is the ", "MOST", "LEAST", " capitalist"],
    ["is the ", "MOST", "LEAST", " angry"],
    ["is the ", "MOST", "LEAST", " hungry"],
    ["is the ", "MOST", "LEAST", " godly"],
    ["is the ", "MOST", "LEAST", " manly"],
    ["has the ", "MOST", "LEAST", " midnight energy"],
    ["has the ", "MOST", "LEAST", " farm-to-table energy"],
    ["has the ", "MOST", "LEAST", " accurate title"],
    ["has the ", "MOST", "LEAST", " moth energy"],
    ["has the ", "MOST", "LEAST", " bear energy"],
    ["has the ", "MOST", "LEAST", " bat energy"],
    ["has the ", "MOST", "LEAST", " wolf energy"],
    ["is the ", "MOST", "LEAST", " goblin mode"],
    ["has the ", "MOST", "LEAST", " stars"],
    ["has the ", "MOST", "LEAST", " athletic cast"],
    ["has the ", "MOST", "LEAST", " lazer energy? pew pew"],
    ["is ", "MOST", "LEAST", " memeable"],
    ["is the ", "MOST", "LEAST", " robotic"],
    ["is the ", "MOST", "LEAST", " down-to-Earth"],
    ["has the ", "MOST", "LEAST", " creatures"],
    ["has the ", "MOST", "LEAST", " lunar energy"],
    ["is the ", "MOST", "LEAST", " family-friendly"],
    ["has the ", "MOST", "LEAST", " exotic locations"],
    ["is the ", "MOST", "LEAST", " aquatic"],
    ["has the ", "MOST", "LEAST", " mall-walker energy"],
    ["has the ", "MOST", "LEAST", " gas"],
    ["is the ", "MOST", "LEAST", " heavy metal"],
    ["is the ", "MOST", "LEAST", " hip-hop"],
    ["is the ", "MOST", "LEAST", " electronic"],
    ["has the ", "MOST", "LEAST", " folk energy"],
    ["is the ", "MOST", "LEAST", " classical"],
    ["is the ", "MOST", "LEAST", " British"],
    ["is the ", "MOST", "LEAST", " grunge"],
    ["is the ", "MOST", "LEAST", " brainy"],
    ["is the ", "MOST", "LEAST", " ballet-like"],
    ["is the ", "MOST", "LEAST", " operatic"],
    ["is the ", "MOST", "LEAST", " orchestral"],
    ["has the ", "MOST", "LEAST", " Disney energy"],
    ["has the ", "MOST", "LEAST", " epic quest"],
    ["is the ", "MOST", "LEAST", " likely to be name-dropped in a rap"],
]


movieList = [
    "Son of Dracula (1943)",
    "The Monster That Challenged The World (1957)",
    "Critters 4 (1992)",
    "The Golden Voyage of Sinbad (1973)",
    "Jason and the Argonauts (1963)",
    "The Adventures of Hercules (1985)",
    "Hercules (1983)",
    "Dr. Who and the Daleks (1965)",
    "4D Man (1959)",
    "Devil Doll (1964)",
    "Planet Earth (1974)",
    "The Quatermass Xperiment (1955)",
    "Mothra (1961)",
    "Godzilla (1998)",
    "Death Race 2000 (1975)",
    "Time Walker (1982)",
    "Tales from the Crypt (1972)",
    "The She-Creature (1956)",
    "Attack of the Puppet People (1958)",
    "The Asphyx (1972)",
    "Space Master X-7 (1958)",
    "Alligator (1980)",
    "Vampires on Bikini Beach (1988)",
    "Critters 3 (1991)",
    "The Howling (1981)",
    "Pumpkinhead (1988)",
    "The Hunger (1983)",
    "Fright Night (1985)",
    "The Food of the Gods (1976)",
    "The Angry Red Planet (1959)",
    "Creature from the Black Lagoon (1954)",
    "The Man from Planet X (1951)",
    "Grizzly (1976)",
    "Swamp Thing (1982)",
    "The Little Shop of Horrors (1960)",
    "Godzilla, Mothra and King Ghidorah: Giant Monsters All-Out Attack (2001)",
    "The Raven (1963)",
    "Vampire Circus (1972)",
    "Maximum Overdrive (1986)",
    "X: The Man with the X-Ray Eyes (1963)",
    "Frankenstein Meets the Space Monster (1965)",
    "Clash of the Titans (1981)",
    "Starcrash (1978)",
    "Bog (1979)",
    "Dracula, Prisoner of Frankenstein (1972)",
    "Godzilla: Final Wars (2004)",
    "Forbidden Planet (1956)",
    "Beyond Atlantis (1973)",
    "Slugs (1988)",
    "The Gate (1987)",
    "The Bat People (1974)",
    "First Men in the Moon (1964)",
    "Krull (1983)",
    "Laserblast (1978)",
    "Cat Girl (1957)",
    "Critters 2 (1988)",
    "Yeti: The Giant of the 20th Century (1977)",
    "Critters (1986)",
    "C.H.U.D. (1984)",
]


def get_random_question():
    template = random.choice(movieCriteria)
    # Randomly pick index 1 or 2 (the polarities)
    polarity = random.choice([template[1], template[2]])
    return f"Which movie {template[0]}{polarity}{template[3]}?"


def getMovieHashtag(titleParenthesesDate):
    # This regex finds everything that IS NOT a letter or a number
    # and replaces it with an empty string.
    clean_title = re.sub(r"[^a-zA-Z0-9]", "", titleParenthesesDate)
    return f"#{clean_title}"


def addEllipsisIfTooLong(word):
    if len(word) > 50:
        word = word[:49] + "…"
    return word


def main():
    emojis = [
        "🚨",
        "🧟",
        "👾",
        "👺",
        "☢️",
        "💀",
        "🦇",
        "🏚️",
        "🧪",
        "🎥",
        "🔥",
        "🎬",
        "🎞️",
        "🍿",
        "🧛",
        "🛸",
        "🤢",
        "🩸",
        "😱",
        "👻",
        "👽",
        "🎃",
        "👹",
    ]

    movie1, movie2 = random.sample(movieList[:52], 2)
    # question = random.choice(movieCriteria)
    movie1 = addEllipsisIfTooLong(movie1)
    movie2 = addEllipsisIfTooLong(movie2)
    poll = mastodon.make_poll(
        options=[movie1, movie2], expires_in=86400, multiple=False
    )
    e1, e2 = random.sample(emojis, 2)
    post_text = f"{e1}{e2} MARS MADNESS POLL {e2}{e1} {get_random_question()}\n\n#monsterdon #MarsMadness {getMovieHashtag(movie1)} {getMovieHashtag(movie2)}"
    print(post_text)
    mastodon.status_post(
        status=f"{post_text}",
        poll=poll,
        visibility="public",
    )


if __name__ == "__main__":
    main()
# for i in range(20):
#     print(get_random_question())
