from mastodon import Mastodon
from dotenv import load_dotenv
import os, random, re

load_dotenv()

mastodon = Mastodon(
    client_id=os.getenv("client_key"),
    client_secret=os.getenv("client_secret"),
    access_token=os.getenv("access_token"),
    api_base_url="https://mastodon.social",
)

movieCriteria = [
    "Which movie feels the LEAST likely to pass the Bechdel test?",
    "Which movie feels the MOST like a cash grab?",
    "Which movie feels the MOST like a ripoff of a better film?",
    "Which movie feels the MOST made-for-tv?",
    "Which movie feels the MOST outdated?",
    "Which movie had the MOST wasted potential?",
    "Which movie has the BIGGEST baddie?",
    "Which movie has the CHEAPEST looking sets?",
    "Which movie has the FEWEST deaths?",
    "Which movie has the FEWEST famous actors?",
    "Which movie has the LEAST action?",
    "Which movie has the LEAST amount of actual monster footage?",
    "Which movie has the LEAST amount of effort?",
    "Which movie has the LEAST blood?",
    "Which movie has the LEAST coffee served?",
    "Which movie has the LEAST competent heroes?",
    "Which movie has the LEAST consistent monster size?",
    "Which movie has the LEAST conventional weapon?", 
    "Which movie has the LEAST convincing-looking monster?",
    "Which movie has the LEAST dangerous monster?",
    "Which movie has the LEAST destruction?",
    "Which movie has the LEAST effective military or police?"
    "Which movie has the LEAST famous director?",
    "Which movie has the LEAST fur?",
    "Which movie has the LEAST monster screen time?",
    "Which movie has the LEAST rizz?",
    "Which movie has the LEAST romance?",
    "Which movie has the LEAST screams?",
    "Which movie has the LEAST threatening monster?",
    "Which movie has the MOST 'Damsel in Distress' energy?",
    "Which movie has the MOST 'Mad Scientist' energy?",
    "Which movie has the MOST abrupt ending?",
    "Which movie has the MOST aggressive Male Gaze?",
    "Which movie has the MOST annoying dialogue?",
    "Which movie has the MOST awkwardly-moving monster?",
    "Which movie has the MOST boring filler scenes?",
    "Which movie has the MOST cartoonish-looking monster?",
    "Which movie has the MOST chewed scenery?",
    "Which movie has the MOST confusing geography?",
    "Which movie has the MOST confusing monster rules?",
    "Which movie has the MOST confusing plot?",
    "Which movie has the MOST fake rocks?",
    "Which movie has the MOST nonsensical science?",
    "Which movie has the MOST plot holes?",
    "Which movie has the MOST sandals?",
    "Which movie has the MOST toxic masculinity?",
    "Which movie has the MOST toxic vibe?",
    "Which movie has the MOST unnecessary scenes?",
    "Which movie has the MOST unnecessary slow-motion?",
    "Which movie has the SLOWEST monster?",
    "Which movie has the SMALLEST baddie?",
    "Which movie has the STUPIDEST character decisions?",
    "Which movie has the WORST acting?",
    "Which movie has the WORST characters?",
    "Which movie has the WORST cinematography?",
    "Which movie has the WORST costume and production design?",
    "Which movie has the WORST ending?",
    "Which movie has the WORST hero?",
    "Which movie has the WORST monster/creature design?",
    "Which movie has the WORST music and sound design?",
    "Which movie has the WORST night scenes?",
    "Which movie has the WORST plot twist?",
    "Which movie has the WORST story/script?",
    "Which movie has the WORST title?",
    "Which movie has the WORST visual effects/CGI?",
    "Which movie is the BIGGEST disaster?",
    "Which movie is the LEAST complex?",
    "Which movie is the LEAST dark?",
    "Which movie is the LEAST dramatic?",
    "Which movie is the LEAST epic?",
    "Which movie is the LEAST erotic?",
    "Which movie is the LEAST fun?",
    "Which movie is the LEAST funny?",
    "Which movie is the LEAST interesting?",
    "Which movie is the LEAST likely to become a cult classic?",
    "Which movie is the LEAST memorable?",
    "Which movie is the LEAST original?",
    "Which movie is the LEAST powerful?",
    "Which movie is the LEAST professional?",
    "Which movie is the LEAST rewatchable?",
    "Which movie is the LEAST scary?",
    "Which movie is the LEAST thought-provoking?",
    "Which movie is the LEAST violent?",
    "Which movie is the MOST angsty?",
    "Which movie is the MOST annoying?",
    "Which movie is the MOST athletic?",
    "Which movie is the MOST camp?",
    "Which movie is the MOST cheap?",
    "Which movie is the MOST cheesy?",
    "Which movie is the MOST childish?",
    "Which movie is the MOST Corman-esque?",
    "Which movie is the MOST cringe?",
    "Which movie is the MOST cursed?",
    "Which movie is the MOST destructive?",
    "Which movie is the MOST disappointing?",
    "Which movie is the MOST dusty?",
    "Which movie is the MOST dystopian?",
    "Which movie is the MOST embarrassing?",
    "Which movie is the MOST fake?",
    "Which movie is the MOST fictional?",
    "Which movie is the MOST gothic?",
    "Which movie is the MOST graphic?",
    "Which movie is the MOST hideous?",
    "Which movie is the MOST Jaws-esque?",
    "Which movie is the MOST lazy?",
    "Which movie is the MOST nerdy?",
    "Which movie is the MOST offensive?",
    "Which movie is the MOST pointless?",
    "Which movie is the MOST predictable?",
    "Which movie is the MOST radioactive?",
    "Which movie is the MOST religious?",
    "Which movie is the MOST Satanic?",
    "Which movie is the MOST sleazy?",
    "Which movie is the MOST small?",
    "Which movie is the MOST stiff?",
    "Which movie is the MOST teen?",
    "Which movie is the MOST thirsty?",
    "Which movie is the MOST tone deaf?",
    "Which movie is the MOST trashy?",
    "Which movie is the MOST unnecessary?",
]


movieList = [
    "Hercules (1983)",
    "Dr. Who and the Daleks (1965)",
    "4D Man (1959)",
    "Devil Doll (1964)",
    "Planet Earth (1974)",
    "The Quatermass Xperiment (1955)",
    "Mothra (1961)",
    "Godzilla (1998)",
    "Death Race 2000 (1975)",
    "Time Walker (1982)",
    "Tales from the Crypt (1972)",
    "The She-Creature (1956)",
    "Attack of the Puppet People (1958)",
    "The Asphyx (1972)",
    "Space Master X-7 (1958)",
    "Alligator (1980)",
    "Vampires on Bikini Beach (1988)",
    "Critters 3 (1991)",
    "The Howling (1981)",
    "Pumpkinhead (1988)",
    "The Hunger (1983)",
    "Fright Night (1985)",
    "The Food of the Gods (1976)",
    "The Angry Red Planet (1959)",
    "Creature from the Black Lagoon (1954)",
    "The Man from Planet X (1951)",
    "Grizzly (1976)",
    "Swamp Thing (1982)",
    "The Little Shop of Horrors (1960)",
    "Godzilla, Mothra and King Ghidorah: Giant Monsters All-Out Attack (2001)",
    "The Raven (1963)",
    "Vampire Circus (1972)",
    "Maximum Overdrive (1986)",
    "X: The Man with the X-Ray Eyes (1963)",
    "Frankenstein Meets the Space Monster (1965)",
    "Clash of the Titans (1981)",
    "Starcrash (1978)",
    "Bog (1979)",
    "Dracula, Prisoner of Frankenstein (1972)",
    "Godzilla: Final Wars (2004)",
    "Forbidden Planet (1956)",
    "Beyond Atlantis (1973)",
    "Slugs (1988)",
    "The Gate (1987)",
    "The Bat People (1974)",
    "First Men in the Moon (1964)",
    "Krull (1983)",
    "Laserblast (1978)",
    "Cat Girl (1957)",
    "Critters 2 (1988)",
    "Yeti: The Giant of the 20th Century (1977)",
    "Critters (1986)",
    "C.H.U.D. (1984)",
]

def getMovieHashtag(titleParenthesesDate):
    # This regex finds everything that IS NOT a letter or a number
    # and replaces it with an empty string.
    clean_title = re.sub(r'[^a-zA-Z0-9]', '', titleParenthesesDate)
    return f"#{clean_title}"

def main():
    emojis = ["🚨","🧟", "👾", "👺", "☢️", "💀", "🦇", "🏚️", "🧪", "🎥", "🔥", "🎬", "🎞️", "🍿", "🧛", "🛸","🤢","🩸","😱","👻","👽","🎃","👹"]
        
    movie1, movie2 = random.sample(movieList, 2)
    question = random.choice(movieCriteria)
    
    poll = mastodon.make_poll(
        options=[movie1, movie2],
        expires_in=86400, 
        multiple=False
    )
    e1, e2 = random.sample(emojis, 2)
    post_text = f"{e1}{e2} MARCH BADNESS POLL {e2}{e1} {question}\n\n#monsterdon #MarchBadness {getMovieHashtag(movie1)} {getMovieHashtag(movie2)}" 
    mastodon.status_post(
        status=f'{post_text}',
        poll=poll,
        visibility="public",
    )

if __name__ == "__main__":
    main()
