from mastodon import Mastodon
from dotenv import load_dotenv
import os, json, re, html, time
from bs4 import BeautifulSoup
import random
from PIL import Image, ImageDraw, ImageFont

# load_dotenv()
# TEMP_PNG_PATH = os.getenv("TEMP_PNG_PATH", "/tmp/devilgirl.png")  # fallback default
# LAST_ID_FILE = os.getenv("LAST_ID_FILE", "/tmp/last_id.txt")  # fallback default
# LAST_RANDOM_POST_FILE = os.getenv("LAST_RANDOM_POST_FILE", "/tmp/last_random_post.txt")
# IMAGES_FOLDER = os.getenv("IMAGES_FOLDER", "/path/to/images")  # fallback default
# FONT_PATH = os.getenv("FONT_PATH", "/path/to/default/font.ttf")
# FONT_SIZE = int(os.getenv("FONT_SIZE", 46))  # convert to int
# POST_INTERVAL = 2 * 60 * 60  # 2 hours

captions = [
    ":3",
    "?!",
    "*internal screaming*",
    "*jazz music stops*",
    "*panic internally*",
    "*screams into void*",
    "*SUPER*STAR*",
    "10/10",
    "100%",
    "404 brain not found",
    "Adulting: Nope",
    "Aight Imma Head Out",
    "Ain't nobody got time for that",
    "Aliens watch me for tips",
    "all your base are belong to us",
    "Anxiety but make it aesthetic",
    "ANYONE NEED BUTTER?",
    "ARE YOU GOING TO STUDY HALL?",
    "Aww Yea",
    "Bad Hair, Don't Care",
    "Be careful, I know how to change the wifi password",
    "Be kind, I'm doing my best",
    "Be nice, I might be your tech support someday",
    "Be right back, disassociating",
    "Bet",
    "Big brain energy, small body",
    "Big brain time",
    "Big Mood",
    "Big oof",
    "Big yawn, bigger vibes",
    "Big Yikes",
    "Binary mood: 101010",
    "Bless this mess",
    "Brain lag loading...",
    "brb, debugging life",
    "BRB: existential crisis",
    "BRB: Mentally elsewhere",
    "Breakdancing Champ",
    "Bro Do You Even Lift?",
    "Bro got the quantum Ohio gyatt buff",
    "Bro said skill issue",
    "Bruh Moment",
    "Bruh",
    "BYEEEEEE",
    "cache rules everything around me",
    "Caffeine and kindness",
    "Can't adult today, send help",
    "Can't even",
    "Can't stop, won't stop",
    "Can't touch this literally",
    "Can't unsee",
    "Catch me if you can",
    "Catch me in the cache",
    "Catch these hands",
    "Certified Goofy Ahh Energy",
    "Certified Lover Era Human",
    "Certified rizz mage from Ohio",
    "Champagne problems but make it cute",
    "Chronically online but tired of it",
    "Clownin",
    "Coffee a little, laugh a lot",
    "Coffee: because adulting is hard",
    "come at me bro",
    "Commit early, commit often",
    "Cringe",
    "Ctrl + Alt + Del my problems",
    "Currently avoiding responsibilities",
    "Currently vibing... maybe",
    "Cursed Image",
    "Decaf? No thanks, I'm not a quitter",
    "Delete This",
    "Demure",
    "Derp",
    "Do You Like My Sword",
    "Don't @ me",
    "Don't follow me, I'm lost too",
    "Don't Follow Me, I'm Lost Too",
    "don't talk to me or my son ever again",
    "Eat, Sleep, Repeat",
    "Eat, sleep, repeat",
    "Emotional support hoodie",
    "Error 404: Motivation Not Found",
    "Error: Fun not found",
    "Espresso yourself",
    "Fallin for u",
    "Family Reunion",
    "Family: where life begins and love never ends",
    "Fanum-powered sigma skibidi sweep",
    "Feeling 22-ish every day",
    "Flexin on em",
    "Forever Alone",
    "Friendship is Magic",
    "Fueled by caffeine and cardigan energy",
    "Gather here with grateful hearts",
    "Get out of my head",
    "Get rekt",
    "git commit -m 'send help'",
    "Gold Medal Winner",
    "Good vibes only",
    "Goofy",
    "GOTTA LOVE BAKED BEANS",
    "Gravity fears my power",
    "Growing up was a trap",
    "Guess I'll go home now",
    "Gyatt alert: skibidi mode activated",
    "Gyatt level 1000 fanum tax moment",
    "Happiness is homemade",
    "Haters Gonna Hate",
    "he chonk",
    "He Protec, but he also Attac",
    "heck yes",
    "HELP ME",
    "Here we go again",
    "High key",
    "Hold on, I need to overthink this",
    "Home is where the WiFi is",
    "Home sweet chaos",
    "Howdy",
    "I Brake for Snacks",
    "I Can't Believe You've Done This",
    "I Can't Unsee This",
    "I can't. I'm in my flop era",
    "I declare... lunchtime!",
    "I did not ask",
    "I don't need Google my spouse knows everything",
    "i guess we doin",
    "I hate it here",
    "I lift tacos, bench press pizza",
    "I Only Cried For 20 Minutes",
    "I paused my game to be here",
    "I regret nothing... yet",
    "I see what you did there",
    "I speak fluent movie quotes",
    "I turn coffee into code",
    "I void contracts",
    "I void warranties",
    "I want to speak to your manager!",
    "I'm a box",
    "I'm a cutie",
    "I'm baby",
    "I'm in danger",
    "I'm kind of a big dill",
    "I'm literally built different",
    "I'm not arguing, I'm just explaining why I'm right",
    "I'm not lazy, I'm energy efficient",
    "I'm not short, I'm fun-sized",
    "I'm not superstitious, just a little stitious",
    "I'm okay-ish",
    "I'm on a seafood diet: I see food, and I eat it",
    "I'm shooketh",
    "I'm silently correcting your grammar",
    "I'm so skibidi",
    "Identity theft is NOT a joke, Jim",
    "If it's not on the calendar, it doesn't exist",
    "If you can read this, bring me pizza",
    "Ight, I'mma head out",
    "In my Swiftie era",
    "Instant human: just add coffee",
    "Introverted but willing to discuss cats",
    "Issa vibe",
    "It do be like that sometimes",
    "It was inevitable",
    "It works fine on *my* computer",
    "It's a trap!",
    "It's over 9000!",
    "Just here for the memes",
    "Just Lost My Dawg",
    "Just vibin'",
    "Keep calm and carry on",
    "Kernel panic: adulthood",
    "Kid tested mother approved",
    "Laundry today or naked tomorrow",
    "Let that sink in",
    "Let's taco 'bout it",
    "Life happens, coffee helps",
    "Life is better on the porch",
    "Life is short, git push",
    "LITERALLY ME",
    "Live, Laugh, Love",
    "Living my best NPC life",
    "Low key",
    "Low-power mode activated",
    "Main character energy: activated",
    "Main character in training",
    "Major key",
    "Make It Happen",
    "Maximum Overdrive",
    "May the source be with you",
    "Me, an intellectual",
    "Me: calm. Brain: nah.",
    "Meet me at midnight vibes",
    "Mentally I'm still buffering",
    "Mentally on Do Not Disturb",
    "MOAR!",
    "mom come pick me up",
    "Mood: 404 not found",
    "Mood",
    "Mother",
    "My brain has too many tabs open",
    "My comfort show is my personality now",
    "My disappointment is immeasurable",
    "My Dream",
    "My password is longer than my attention span",
    "My playlist is 90% nostalgia",
    "My shadow scares criminals",
    "My tears? Glitter.",
    "My wifi connects instantly",
    "Nah fam",
    "Nailed it",
    "No Cap",
    "No chill",
    "No Excuses, Just Results",
    "No Maidens?",
    "No shirt, no shoes, no service",
    "No thoughts, just vibes",
    "Nobody:...",
    "Noice",
    "Not Again!",
    "Not like this",
    "Not today, Satan",
    "NPC detected in the Ohio backrooms",
    "NPC? Nah, I'm side-questing",
    "Oh lawd he comin'",
    "Oh no baby, what is you doing?",
    "Ohio sigma energy: unpatched",
    "OK Boomer",
    "One does not simply...",
    "Oof",
    "Oops. Did I do that?",
    "Outta Office, Into Nature",
    "Ping me if you dare",
    "Please excuse the mess, my kids are making memories",
    "Please help me",
    "Plot twist: I'm the villain",
    "Plot twist",
    "poor lil guy",
    "Powered by caffeine and chaos",
    "Powered by Coffee and Gasoline",
    "Powered by friendship bracelets",
    "Powered by snacks and questionable decisions",
    "Poyo",
    "Pretzel Day Enthusiast",
    "Procaffinating: the tendency to not start anything until you've had coffee",
    "Procrastinators unite... tomorrow",
    "Professional overthinker",
    "Quantum brain loading",
    "Ratatouille",
    "Rats!",
    "rm -rf / (just kidding)",
    "Road Trip Mood Activated",
    "Running late is my cardio",
    "Running on coffee and dry shampoo",
    "Running on vibes and iced coffee",
    "Sarcasm: just one of my many talents",
    "Sassy since birth",
    "Say what?",
    "Scrolling is my cardio",
    "See ya tomorrow",
    "Send it!",
    "Sending Good Vibes",
    "Shake it. Don't break it.",
    "Shook",
    "Simmering chaos inside",
    "Skibidi rizzplosion in progress",
    "Skibidi sigma rizzler Ohio core",
    "Smile, it confuses people",
    "Social battery: 1%",
    "Sorry, not sorry",
    "Spillin' the tea",
    "Stack overflowed my emotions",
    "Straight up",
    "Stressed, blessed, and coffee obsessed",
    "sudo make me a sandwich",
    "sudo rm -rf regrets",
    "Suns Out, Hats On",
    "Surviving on caffeine and chaos",
    "SUS",
    "Syntax error: too tired",
    "Take me tubing!",
    "Talk nerdy to me",
    "TEETH",
    "Thanks, I Hate It",
    "Thas Tough",
    "That's a lotta damage",
    "That's Hot",
    "The dog is in charge",
    "The Guy From Fortnite?",
    "the legend",
    "Theyre in the walls",
    "This ain't it, chief",
    "This Hat Paid for Itself",
    "This is a nightmare",
    "THIS IS FINE!",
    "This Is Fine",
    "This is me trying (my best)",
    "This is my 'I tried' outfit",
    "This is my life",
    "This is my too-tired-to-function shirt",
    "This is my weekend look",
    "This is Ohio",
    "This is sus",
    "This is the ideal male body",
    "This is where the fun begins",
    "This kitchen is seasoned with love",
    "This might be coffee",
    "Time is irrelevant",
    "Too Cool for Your Rules",
    "Too much Monday, not enough coffee",
    "Too much sauce, not enough spaghetti",
    "Touch grass? I barely touch sleep",
    "Ultra-mega-goofy skibidi rizz",
    "Unexpected Item in Bagging Area",
    "UwU",
    "Vibe Check",
    "Vibing in the chat",
    "W rizz, L sleep schedule",
    "Wait, what?",
    "Warning: May start talking about my hobby at any time",
    "wat?",
    "We Stan",
    "Weird champ",
    "Weird Flex But Okay",
    "Welcome-ish: Depends on who you are",
    "Welp",
    "when u hear a noise at night",
    "When will you learn?",
    "When you realize...",
    "Who Put You on the Planet?",
    "Whole vibe",
    "Why am I like this?",
    "Why are we here, just to suffer?",
    "Why though?",
    "Woke up and chose violence",
    "Women want me, fish fear me",
    "World's Best Whatever",
    "Y'all Got Any More Of That?",
    "Yeeeee Haw!",
    "Yeet",
    "Yikes forever",
    "You can't scare me, I have kids",
    "You had one job",
    "You love to see it",
    "You Serve",
    "You're doing amazing, sweetie",
    "Zero chill",
    "Zero Plans, All Vibes",
    "Lowkey vibing, don't mind me",
    "Big bet, say less",
    "This whole thing is lit",
    "Stay salty, my friend",
    "Feeling Gucci today fr fr",
    "Squad goals on maximum mode",
    "Weird flex but okay, buddy",
    "Zero chill, full savage mode",
    "Brows on fleek forever",
    "Quit throwing shade, amateur",
    "You big mad, not me",
    "All the feels right now",
    "Yeet it into space",
    "Ghost ride my whip gently",
    "Drip too powerful, beware",
    "Don't simp, stay sigma",
    "Yep, it's a bop",
    "Low key go off, queen",
    "Cheugy but still iconic",
    "We stan chaotic energy",
    "Kept it litty all day",
    "You're so extra today",
    "Keep it hunid always",
    "High key fire content",
    "Flex on them haters daily",
    "Major vibes detected rn",
    "Everything is mid today",
    "This combo is pog",
    "The vibe has shifted",
    "Time for a vibe check",
    "Vibe is up, clearly",
    "Thas tough, can't lie",
    "Sussy Bakka energy detected",
    "Truth only, no cap",
    "Sip lean responsibly, bro",
    "Real ones only, fr fr",
    "You looking thirsty, chill",
    "Certified thirst trap moment",
    "This meal is bussin fr",
    "Goofy ahh behavior rn",
    "Absolute unit approaching",
    "Periodt, end of discussion",
    "Point blank period, sis",
    "That was a serve, honestly",
    "You ate without crumbs",
    "You serve every day",
    "Serving chaotic-adjacent energy",
    "You thought, but no",
    "Nonchalant but still iconic",
    "Full sigma mindset activated",
    "lowkey your planet is ours",
    "bet we conquer by sunrise",
    "lit invasion protocols engaged",
    "salty humans detected",
    "our gucci warships approach",
    "squad pulling up in orbit",
    "weird flex but okay, resist",
    "savage beam cannons charging",
    "battle formation on fleek",
    "throwing shade on your defenses",
    "big mad your shields failed",
    "feels like easy victory",
    "yeet your leaders into space",
    "ghost ride my whip through your skies",
    "alien drip too advanced",
    "simp for your resources",
    "your distress signal? it's a bop",
    "low key go off, troops",
    "your tech is cheugy",
    "we stan planetary domination",
    "kept it litty with orbital strikes",
    "so extra, building bunkers",
    "keep it hunid, surrender",
    "your downfall high key fire",
    "flex on them haters, fleet",
    "our invasion vibes immaculate",
    "your resistance is mid",
    "our weaponry is pog",
    "vibe has shifted—prepare",
    "vibe check failed, Earthlings",
    "vibe is up—attack mode",
    "thas tough, humanity",
    "Sussy Bakka trying to hide",
    "invading with no cap",
    "Lean to dodge the lasers",
    "prepare, fr fr",
    "your oceans looking thirsty",
    "your satellites are a thirst trap",
    "our engines bussin fr",
    "goofy ahh defenses fr",
    "mothership is an absolute unit",
    "your empire ends, periodt",
    "planet secured, point blank period",
    "that was a serve, fleet",
    "you ate those missiles though",
    "you serve panic well",
    "serving intergalactic realness",
    "You thought you could win",
    "invading nonchalant vibes only",
    "sigma squad descending now",
    "Who can draw the line?",
    "Who can draw any line?",
    "This is all very well.",
    "Six Seven",
    "Man is a machinate mammal.",
    "I would not urge more than this.",
    "His memory goes in his pocket-book.",
    "Less than this will be insufficient.",
    "A mollusc has not much consciousness.",
    "These machines have made us what we are.",
    "If so, what will they not in the end become?",
    "Yet in the course of time consciousness came.",
    "Is not everything interwoven with everything?",
    "Where does consciousness begin, and where end?",
    "Is there not a power cycle process everywhere?",
    "May not the world last twenty million years longer?",
    "How greatly do we not now live with our external limbs?",
    "The largest of them will probably greatly diminish in size.",
    "If this is unconsciousness, where is the use of consciousness?",
    "But who can say that the robot has not a kind of consciousness?",
    "The present machines are to the future as the early Saurians to man.",
    "Is not machinery linked with humanity in an infinite variety of ways?",
    "Herein lies the fundamental difference between man and his inferiors.",
    "Who lowkey gonna draw the line tho?",
    "Like fr, can anybody even draw a line?",
    "This whole situation? Kinda lit, not gonna lie.",
    "Six seven? Bet.",
    "Man is basically a sigma mammal with drip.",
    "I'm not gonna flex more than this, fr fr.",
    "His memory? Bro keeps it in his goofy ahh Notes app.",
    "Anything less is mid, no cap.",
    "A mollusc got like... zero vibes, point blank periodt.",
    "These machines really made us who we are... weird flex but okay.",
    "If that's true, what are they gonna be cooking up next? High key scary.",
    "But over time, consciousness lowkey pulled up.",
    "Isn't everything linked with everything? Big squad energy.",
    "Where do vibes begin and where do they ghost? Asking fr.",
    "Is there not a whole vibe cycle happening everywhere?",
    "Maybe the world still got like twenty mil years left, no big deal.",
    "Crazy how we live with our external limbs now kinda extra.",
    "The biggest ones gonna shrink down eventually absolute unit no more.",
    "If that's unconsciousness, then what's the point of being woke? No cap.",
    "But who's to say robots don't have like... some sussy consciousness?",
    "Today's machines are basically early dinos compared to whatever's coming thas tough.",
    "Aren't machines and humans linked in infinite ways? Big vibes.",
    "And THAT right there is the difference between us and the NPCs, periodt.",
    "My name is Nyah.",
    "You men on Earth are much as we expected.",
    "You are a scientist?",
    "You are a very poor physical specimen.",
    "Yes, this is the first landing.",
    "The course was set for London, but the planet's atmosphere was thicker than expected.",
    "A part of the ship was torn off.",
    "Repairs will take about four Earth hours.",
    "Johnny is with me.",
    "Johnny is a mechanical man.",
    "A robot, with many of the characteristics of a human.",
    "Improved by an electronic brain.",
    "The metal from which the spaceship is constructed can reproduce itself.",
    "Many of your Earth years ago, our women were similar to yours today.",
    "Our emancipation took several hundred years, and ended in a bitter devastating war between the sexes.",
    "The last war we ever had.",
    "All inhabited planets have had wars.",
    "Some have ended by wiping themselves out.",
    "For every new weapon invented, a defense was perfected.",
    "The ultimate weapon was developed.",
    "A perpetual motion chain reactor beam.",
    "As fast as matter was created, it was changed by its molecular structure into the next dimension and so destroyed itself.",
    "After the War of the Sexes, women became the rulers of Mars.",
    "The male is fallen into a decline.",
    "The birth rate is dropping tremendously.",
    "Despite our advanced science, we have still found no way of creating life.",
    "On Mars, some think I will not return, that the metal is too unstable.",
    "When I get back we will build more spaceships.",
    "I will select some of your strongest men to return with me to Mars.",
    "There is no, if.",
    "The nuclear ship contains a paralyzer ray mechanism capable of freezing all life over a wide area.",
    "Mars offers the scientific millennium, now.",
    "He was superfluous, a hopeless specimen.",
    "Do not try to follow me, you cannot get help.",
    "Around this house I've drawn an invisible wall through which no one may pass, in or out.",
    "You're all very quiet.",
    "No doubt you're resigned to the inevitable.",
    "I observed your encounter with the electronic wall.",
    "Today, it is you who learn learn the power of Mars.",
    "Tomorrow, it will be the whole world.",
    "You fool.",
    "You poor demented humans.",
    "To imagine you can destroy me with your old-fashioned toy.",
    "What do you know of force?",
    "Forces that we use on Mars.",
    "You shall know.",
    "You and the rest who dwell on this planet.",
    "I can control power beyond your wildest dreams.",
    "Come and you shall see!",
    "Now, Earth men, look.",
    "Watch the power of another world!",
    "You speak in riddles.",
    "You should plead for your own life and not for his.",
    "He will be safe with me.",
    "You ask a lot of questions.",
    "I will deal with you later.",
    "Come, we will return to the ship.",
    "You speak unwisely.",
    "I will show you wonders you have never seen before.",
    "No doubt you are having a council of war.",
    "It amuses me to watch your puny efforts.",
    "It would take you 1,000 years to learn a fragment of what we have achieved.",
    "None to equal those of Mars.",
    "You say you believe the evidence of your senses.",
    "Very well then, you shall see.",
    "Perhaps then you will realize your helplessness.",
    "Now you shall see.",
    "That was caused by the friction as we entered the atmosphere of the Earth at over 6,000 semantics.",
    "You have no wisdom.",
    "The entire structure of a nuclear ship is made of a new organic metal.",
    "Each molecular cell can absorb its own amount of heat or cold.",
    "It could have absorbed all the heat in a matter of seconds.",
    "Fill your eyes Earth man.",
    "See such powers as you never dreamed existed.",
    "Now, look again.",
    "The evidence of your own eyes, professor.",
    "Can you still see?",
    "There is a enough power there to drive this ship anywhere in the universe.",
    "Enough power to obliterate this speck of matter you call Earth.",
    "Something you scientists have not yet dreamed of.",
    "A form of nuclear fission on a static negative condensity.",
    "Your atomic bomb is positive. Causing the explosion to expand upwards and evaporate.",
    "Our force is negative and explodes the atomic forces into each other, thereby magnifying the power a thousand fold.",
    "The excess reaction of each drive expands and it causes the same motion to happen again and again.",
    "This is what you call perpetual motion.",
    "You talk like a primitive savage.",
    "Because your science has not discovered these things does not mean they're impossible.",
    "Even inventions as radio and television you would have considered impossible 100 years ago.",
    "Now, we shall return to the others.",
    "You fools.",
    "Do you think you can hurt me with this?",
    "Even your limited intelligence should convince you by now that you cannot harm me.",
    "Perhaps your scientists will help to convince you.",
    "Now you must cease your stupid tricks.",
    "You have seen some of my power.",
    "Perhaps this will help to show the others.",
    "You still doubt?",
    "The transfers of men into the fourth dimension is simple.",
    "He is a young creature.",
    "His mind is free from your stupid emotions and fears.",
    "If I take him, he will make a willing subject.",
    "It is time, Earth man.",
    "He is returning with me to Mars of his own free will.",
    "You made your bargain, do not regret it.",
    "It is better for you and your people to know how helpless they are.",
    "The tricks they tried.",
    "How childish they were.",
    "Nothing can resist this power.",
    "That was the last trick, Earth man.",
    "He tried to gain control of the robot.",
    "Because of his trickery you will all suffer.",
    "Do you hear, Earth man?",
    "You have brought shame upon all in this room.",
    "In a few minutes, as you calculate time, the nuclear ship will have repaired itself.",
    "When I leave, this house and everyone in it, will be destroyed.",
    "It is only right that Mars, with it's superior knowledge should triumph over Earth.",
    "Mars will triumph.",
    "I will spare no one.",
    "I will take one of you.",
    "Three times already during this Earth night you've tried to trick me.",
    "That will not happen again!",
    "No one will go into the nuclear ship till it is ready.",
    "I will return soon.",
    "One of you will come with me.",
    "They are afraid.",
    "Do you go with me, of your own free will?",
    "My name's Nyah, lowkey.",
    "You Earth men acting exactly how we expected, no cap.",
    "You a scientist or just pretending for the vibes?",
    "Bro, you're a goofy ahh physical specimen, fr fr.",
    "Yeah, this is our first landing kept it litty tho.",
    "We aimed for London but your planet's thicc atmosphere said nah",
    "Part of the ship yeeted itself off.",
    "Parta the ship just yeeted off.",
    "Repairs gonna take like four Earth hours bet.",
    "Johnny's rolling nonchalant with the squad.",
    "Johnny's a full-on nonchalant mechanical man big pog energy.",
    "A robot with human vibes, improved by that electronic brain drip.",
    "The metal our ship's made of? Lowkey self-replicating, kinda sigma.",
    "Back in the day our women were mid like yours now we savage",
    "Our glow-up took centuries and ended in a savage gender war thas tough.",
    "Last war ever, point blank period.",
    "Every planet with people got war lore, feels.",
    "Some of them wiped themselves out goofy ahh behavior.",
    "Each new weapon got a counter weird flex but okay.",
    "Then we made the ultimate weapon bussin' and terrifying.",
    "A perpetual-motion chain-reactor beam high key fire.",
    "Matter pops in, immediately dips into the next dimension yeet.",
    "After the Sex War, women took over Mars vibes up.",
    "The males? Yeah... they kinda fell off, very mid.",
    "Birth rate dropping hard big mad situation.",
    "Even with all our nonchalant science, we sussy bakka.",
    "Some on Mars think I won't return 'cause the metal unstable salty.",
    "But once I'm back, we're building more ships squad expansion.",
    "I'm picking your strongest men to come to Mars keep it hunid.",
    "There is no 'if,' Earth man stop simping",
    "The nuclear ship's got a paralyzer ray freezes everything. On fleek tech.",
    "Mars got the science millennium now it's a bop.",
    "He was extra, useless, a hopeless specimen weird flex existing.",
    "Don't chase me, you can't yeet through the barrier.",
    "I dropped an invisible wall around the house vibes contained.",
    "Invisible wall just dropped",
    "Why y'all so quiet? Vibe has shifted.",
    "Guess you've accepted the inevitable lowkey go off.",
    "I saw you flop against the electronic wall that was a serve.",
    "Today you learn the Mars power tomorrow the whole world eats it.",
    "You goofy fool.",
    "You goofy ahh humans.",
    "Thinking your toy can hurt me You thought.",
    "What do you know about force? Zero drip.",
    "You don't know what we cook up on Mars fr fr.",
    "You will. Dang!",
    "You and everyone on this mid-tier planet.",
    "I control power beyond your wildest dreams sigma flex.",
    "Pull up and see.",
    "Now, Earth men peep this.",
    "Watch the power of another world vibes on max.",
    "You speaking in riddles kinda cheugy.",
    "You should beg for your life instead of his point blank period.",
    "He's safe with me no cap.",
    "Dang, you ask too many questions thirsty behavior.",
    "Imma deal with you later bet.",
    "Come on, we heading back to the ship squad move.",
    "You talking unwisely throwing shade at yourself.",
    "Imma show you wonders you've never seen serving cosmic energy.",
    "What, having a council of war? That's so extra.",
    "It's hilarious watching your puny efforts absolute unit of failure.",
    "It'd take you 1,000 years to learn a crumb of our science thas tough.",
    "Nothing beats Mars tech flex on them haters.",
    "You say you trust your senses goofy ahh approach but okay.",
    "Alright then, you're gonna see vibe check incoming.",
    "Maybe then you'll realize how helpless you are feels.",
    "Now you gonna see again.",
    "That friction boom? Happened entering your crusty atmosphere at 6,000 semantics lit.",
    "You got no wisdom mid intelligence.",
    "Our ship is built from organic metal high key fire.",
    "Each molecule adjusts to heat or cold drip engineering.",
    "It could've absorbed all heat in seconds bussin tech.",
    "Open your eyes, Earth man take in the vibes.",
    "See powers you never even dreamed existed pog.",
    "Look again vibe is up.",
    "Your own eyes confirming it professor simp.",
    "Still seeing? Good.",
    "This power could take us anywhere in the universe gucci propulsion.",
    "Or wipe out this little Earth speck salty outcome.",
    "Stuff your scientists haven't even dreamed no cap.",
    "Nuclear fission on static negative condensity serving quantum energy.",
    "Your atomic bomb is positive mid explosion.",
    "Ours is negative magnifies power x1000 savage.",
    "Each reaction loops again and again perpetual motion drip.",
    "You sound like a primitive savage goofy ahh vibe.",
    "Just 'cause you don't know it doesn't mean it's fake fr fr.",
    "Radio and TV would've been wild 100 years ago vibe shift.",
    "Now we're going back to the others vibe check pending.",
    "You highkey fools.",
    "You think you can hurt me with that? Weird flex.",
    "Even your limited brains should get you can't harm me lowkey sad.",
    "Maybe your scientists will spell it out for you cheugy learners.",
    "Quit your goofy tricks.",
    "You've seen some of my power just a lil sample.",
    "Maybe this will convince the others periodt.",
    "Still doubting? Big mad energy.",
    "Moving someone to the fourth dimension is easy sigma skillset.",
    "He's young mind free of your thirsty emotions.",
    "If I take him, he'll be down simp-free subject.",
    "It's time, Earth man vibe lock in.",
    "He's coming with me to Mars his own free will, no cap.",
    "You made your bargain don't get salty now.",
    "It's better your people learn their helplessness thas tough.",
    "All the tricks you tried so extra, so childish.",
    "Nothing resists this power absolute unit energy.",
    "That was your last trick, Earth man you ate nothing.",
    "He tried to hack the robot sussy move.",
    "Because of his trickery, you all gonna suffer vibe has shifted.",
    "Ya heard Earth man?",
    "You brought shame on everyone here feels.",
    "In minutes the nuclear ship will repair itself gucci tech.",
    "When I leave, this house and everyone in it gets obliterated point blank period.",
    "Mars wins because Mars got superior knowledge flex on them haters.",
    "Mars will triumph no cap.",
    "Imma spare no one.",
    "Imma take one of you bet.",
    "You tried tricking me three times tonight goofy ahh attempts.",
    "Not happening again sigma lock-in.",
    "No one enters the ship till it's ready boundaries, queen.",
    "Yo, Imma be back soon.",
    "One of you coming with me vibes.",
    "They're scared big scared energy.",
    "Do you come with me of your own free will or nah?" "Attack of the Puppet People",
    "The Vampire Doll",
    "The Monster X Strikes Back: Attack the G8 Summit",
    "The Asphyx",
    "The X from Outer Space",
    "Space Master X-7",
    "Alligator 2: The Mutation",
    "Alligator",
    "Pumpkinhead II: Blood Wings",
    "Vampires on Bikini Beach",
    "Fright Night Part 2",
    "Critters 3",
    "Legend of the Eight Samurai",
    "The Howling",
    "Magic Crystal",
    "Pumpkinhead",
    "Mr. Vampire",
    "The Hunger",
    "Thrilling Bloody Sword",
    "Fright Night",
    "Food of the Gods II",
    "The Food of the Gods",
    "The Angry Red Planet",
    "Revenge of the Creature",
    "Creature from the Black Lagoon",
    "Space Freaks from Planet Mutoid",
    "The Man from Planet X",
    "Grizzly II: Revenge",
    "Grizzly",
    "The Return of Swamp Thing",
    "Swamp Thing",
    "Little Shop of Horrors",
    "The Little Shop of Horrors",
    "Godzilla, Mothra and King Ghidorah: Giant Monsters All-Out Attack",
    "The Raven",
    "Vampire Circus",
    "Trucks",
    "Maximum Overdrive",
    "X: The Man with the X-Ray Eyes",
    "Frankenstein Meets the Space Monster",
    "Clash of the Titans",
    "Starcrash",
    "Bog",
    "Dracula, Prisoner of Frankenstein",
    "Godzilla: Final Wars",
    "Forbidden Planet",
    "Beyond Atlantis",
    "Slugs",
    "The Gate",
    "The Bat People",
    "First Men in the Moon",
    "Krull",
    "Laserblast",
    "Cat Girl",
    "Critters 2",
    "Yeti: The Giant of the 20th Century",
    "Critters",
    "C.H.U.D.",
    "Frogs!",
    "Frogs",
    "The Gorgon",
    "Masters of the Universe",
    "Invasion of the Star Creatures",
    "Piranha",
    "Invasion of the Bee Girls",
    "Battle Beyond the Stars",
    "Devil Girl from Mars",
    "The Stepford Wives",
    "Snowbeast",
    "The Giant Spider Invasion",
    "The Curse of the Aztec Mummy",
    "The Robot vs. The Aztec Mummy",
    "The Phantom Planet",
]

# Extracted Nouns
nouns = [
    "achievement",
    "affair",
    "airliner",
    "alias",
    "Alligator",
    "area",
    "Asphyx",
    "astrophysicist",
    "Atlantis",
    "atmosphere",
    "Attack",
    "Aztec",
    "bar",
    "bargain",
    "barmaid",
    "Bat",
    "Battle",
    "Beach",
    "beam",
    "Bechdel test",
    "Bee",
    "Bikini",
    "birth",
    "Blood",
    "Bog",
    "bomb",
    "brain",
    "C.H.U.D.",
    "Cat",
    "Century",
    "chain",
    "characteristic",
    "Chekhov's gun",
    "Circus",
    "civilisation",
    "Clash",
    "commander",
    "condensity",
    "control",
    "controller",
    "convict",
    "council",
    "course",
    "craft",
    "crash",
    "Creature",
    "Critter",
    "cross",
    "Crystal",
    "Curse",
    "damage",
    "decline",
    "defense",
    "depth",
    "depths",
    "Devil",
    "dimension",
    "double",
    "Dracula",
    "dream",
    "drink",
    "drive",
    "Earth",
    "Earthman",
    "Earthmen",
    "effect",
    "effort",
    "emancipation",
    "emotion",
    "encounter",
    "everyone",
    "exchange",
    "explosion",
    "Eye",
    "fear",
    "fission",
    "Food",
    "fool",
    "Forbidden",
    "force",
    "fragment",
    "Frankenstein",
    "Freak",
    "friction",
    "Fright",
    "Frog",
    "G8",
    "gain",
    "Gate",
    "Ghidorah",
    "Giant",
    "Girl",
    "God",
    "Godzilla",
    "Gorgon",
    "government",
    "Grizzly",
    "ground",
    "grounds",
    "guest",
    "guests",
    "Gun",
    "have",
    "Hennessey",
    "Highlands",
    "Horror",
    "Horrors",
    "hour",
    "hours",
    "house",
    "Howling",
    "human",
    "Hunger",
    "inn",
    "intelligence",
    "Invasion",
    "invention",
    "journalist",
    "King",
    "Krull",
    "Lagoon",
    "landing",
    "Laserblast",
    "Legend",
    "liaison",
    "life",
    "Little",
    "London",
    "lot",
    "lots",
    "Magic",
    "mail",
    "male",
    "Man",
    "man",
    "manner",
    "manor",
    "Mars",
    "Master",
    "Mastodon",
    "matter",
    "Maximum",
    "mechanism",
    "men",
    "metal",
    "meteorite",
    "millennium",
    "mind",
    "model",
    "molecular",
    "Monster",
    "Monsterdon",
    "Moon",
    "moor",
    "moors",
    "Mothra",
    "motion",
    "Mummy",
    "Mutation",
    "Mutoid",
    "nephew",
    "Night",
    "nuclear",
    "Nyah",
    "Overdrive",
    "pair",
    "Part",
    "part",
    "people",
    "People",
    "Phantom",
    "Piranha",
    "plan",
    "planet",
    "Planet",
    "planets",
    "population",
    "power",
    "Prisoner",
    "Professor",
    "Pumpkinhead",
    "Puppet",
    "Puppet People",
    "radio",
    "rate",
    "Raven",
    "ray",
    "raygun",
    "reactor",
    "receptionist",
    "repairs",
    "result",
    "Return",
    "Revenge",
    "road",
    "Robot",
    "robot",
    "room",
    "ruler",
    "sabotage",
    "Samurai",
    "saucer",
    "savage",
    "science",
    "scientist",
    "Scottish Highlands",
    "second",
    "sex",
    "ship",
    "Shop",
    "Slug",
    "Snowbeast",
    "source",
    "Space",
    "spaceship",
    "spare",
    "specimen",
    "speck",
    "Spider",
    "staff",
    "Star",
    "Starcrash",
    "structure",
    "subject",
    "Summit",
    "survivor",
    "Swamp",
    "Sword",
    "take",
    "team",
    "television",
    "Thing",
    "time",
    "Titans",
    "toy",
    "trick",
    "trickery",
    "tricks",
    "triumph",
    "Truck",
    "Universe",
    "universe",
    "Vampire",
    "Vampires",
    "Victory",
    "victory",
    "view",
    "volunteers",
    "wall",
    "war",
    "way",
    "weapon",
    "wife",
    "Wing",
    "Wives",
    "women",
    "wonder",
    "world",
    "X-7",
    "year",
    "Yeti",
    "Vampire Doll",
    "Puppet People",
    "Outer Space",
    "Space Master",
    "Bikini Beach",
    "Fright Night",
    "Red Planet",
    "Black Lagoon",
    "Space Freak",
    "Planet Mutoid",
    "Planet X",
    "Swamp Thing",
    "Little Shop",
    "Vampire Circus",
    "X-Ray Eye",
    "Space Monster",
    "Forbidden Planet",
    "Bat People",
    "Cat Girl",
    "Star Creature",
    "Bee Girl",
    "Stepford Wives",
    "Giant Spider",
    "Aztec Mummy",
    "Phantom Planet",
    "Cat Women",
    "Wrestling Women",
    "Monolith Monster",
    "Blacula",
    "Nosferatu",
    "Count Dracula",
    "Godzilla",
    "Body Snatcher",
    "Wicker Man",
    "Vincent Price",
    "Peter Cushing",
    "Devil Girl",
    "Wrong Frog"
]
names = [
    "Nyah",
    "Devil Girl",
    "Vincent Price",
    "Peter Cushing",
    "Wrong Frog",
    "Space Master",
    "Space Freak",
    "Swamp Thing",
    "Space Monster",
    "Cat Girl",
    "Star Creature",
    "Bee Girl",
    "Giant Spider",
    "Aztec Mummy",
    "Monolith Monster",
    "Blacula",
    "Nosferatu",
    "Count Dracula",
    "Godzilla",
    "Body Snatcher",
    "Wicker Man",
    "Vincent Price",
    "Peter Cushing",
    "Devil Girl",
    "Wrong Frog",
    "Frankenstein"
]
# Extracted Verbs
verbs = [
    "absorb",
    "accompany",
    "achieve",
    "achieved",
    "allow",
    "allows",
    "amuse",
    "amuses",
    "announce",
    "announces",
    "are",
    "are afraid",
    "arm",
    "ask",
    "atone",
    "atoning",
    "Attack",
    "attempt",
    "attempts",
    "be",
    "became",
    "become",
    "be free",
    "believe",
    "believed",
    "be ready",
    "be simple",
    "bring",
    "build",
    "call",
    "came",
    "can absorb",
    "can control",
    "can destroy",
    "can end",
    "can hurt",
    "cannot get",
    "cannot harm",
    "can paralyse",
    "can reproduce",
    "can resist",
    "can see",
    "cause",
    "caused",
    "causing",
    "cease",
    "celebrate",
    "change",
    "come",
    "consider",
    "considered",
    "contain",
    "contains",
    "control",
    "convince",
    "could have absorbed",
    "create",
    "created",
    "creating",
    "deal",
    "decline",
    "declining",
    "destroy",
    "destroyed",
    "develop",
    "die",
    "discover",
    "discovering",
    "do not regret",
    "doubt",
    "do you hear",
    "draw",
    "dream",
    "dreamed",
    "drew",
    "drive",
    "drop",
    "dropping",
    "dwell",
    "effect",
    "effects",
    "enact",
    "encounter",
    "end",
    "ended",
    "enter",
    "entered",
    "entering",
    "enters",
    "equal",
    "escape",
    "evaporate",
    "exist",
    "existed",
    "expand",
    "expands",
    "expect",
    "expected",
    "explode",
    "explodes",
    "fall",
    "fear",
    "fill",
    "find",
    "finds",
    "follow",
    "fool",
    "force",
    "forced",
    "form",
    "forms",
    "freeze",
    "freezing",
    "gain",
    "get back",
    "go",
    "had",
    "happen",
    "happens",
    "has discovered",
    "have",
    "have brought",
    "have ended",
    "have found",
    "have seen",
    "having",
    "head",
    "heads",
    "hear",
    "help",
    "hide",
    "hiding",
    "hope",
    "hoping",
    "hurt",
    "improve",
    "improved",
    "incinerate",
    "incinerates",
    "intimidation",
    "invent",
    "invented",
    "investigate",
    "is",
    "is accompanied",
    "is armed",
    "is fallen",
    "is free",
    "is in love",
    "is ready",
    "is released",
    "is returning",
    "is simple",
    "is thwarted",
    "kidnap",
    "kidnaps",
    "know",
    "land",
    "learn",
    "leave",
    "leaves",
    "look",
    "looking",
    "love",
    "made",
    "magnify",
    "magnifying",
    "make",
    "may pass",
    "mean",
    "meet",
    "must cease",
    "not get",
    "not happen",
    "not harm",
    "not regret",
    "not return",
    "obliterate",
    "observe",
    "observed",
    "off",
    "offer",
    "offers",
    "out",
    "paralyse",
    "pass",
    "perfect",
    "plead",
    "realize",
    "release",
    "repair",
    "replace",
    "reproduce",
    "require",
    "requires",
    "resign",
    "resigned",
    "resist",
    "respond",
    "responds",
    "return",
    "reunite",
    "riddles",
    "run",
    "sabotage",
    "sacrifice",
    "sacrificing",
    "save",
    "say",
    "see",
    "select",
    "send",
    "sends",
    "sent",
    "set",
    "shall know",
    "shall see",
    "should convince",
    "should plead",
    "should triumph",
    "show",
    "snatch",
    "snatching",
    "spare",
    "speak",
    "successfully sabotages",
    "suggest",
    "suggests",
    "take",
    "talk",
    "tear",
    "thicken",
    "thicker",
    "think",
    "thwart",
    "to be caused",
    "to come",
    "to enact",
    "to escape",
    "to go",
    "to land",
    "took",
    "torn",
    "to view",
    "trap",
    "trapping",
    "tried",
    "triumph",
    "try",
    "turn",
    "turning",
    "unwisely",
    "use",
    "vaporise",
    "vaporize",
    "view",
    "volunteer",
    "was",
    "was changed",
    "was developed",
    "was perfected",
    "watch",
    "were",
    "will be",
    "will be destroyed",
    "will build",
    "will deal",
    "will destroy",
    "will die",
    "will end",
    "will go",
    "will have repaired",
    "will help",
    "will",
    "will make",
    "will not happen",
    "will not return",
    "will return",
    "will select",
    "will show",
    "will spare",
    "will take",
    "will triumph",
    "win",
    "wins",
    "wipe",
    "would take",
]

# Extracted Adjectives
adjectives = [
    "poor",
    "physical",
    "first",
    "thicker",
    "mechanical",
    "electronic",
    "similar",
    "bitter",
    "devastating",
    "last",
    "inhabited",
    "new",
    "ultimate",
    "perpetual",
    "molecular",
    "next",
    "male",
    "advanced",
    "unstable",
    "strongest",
    "nuclear",
    "paralyzer",
    "wide",
    "scientific",
    "superfluous",
    "hopeless",
    "invisible",
    "electronic",
    "demented",
    "old-fashioned",
    "wildest",
    "puny",
    "helpless",
    "new",
    "organic",
    "molecular",
    "static",
    "negative",
    "atomic",
    "positive",
    "excess",
    "same",
    "perpetual",
    "primitive",
    "savage",
    "impossible",
    "limited",
    "stupid",
    "young",
    "willing",
    "free",
    "childish",
    "superior",
    "angry",
    "red",
    "black",
    "space",
    "giant",
    "Aztec",
    "phantom",
    "Martian",
    "female",
    "flying",
    "advance",
    "alien",
    "declining",
    "devastating",
    "remote",
    "Scottish",
    "tall",
    "menacing",
    "British",
    "apparent",
    "astrophysicist",
    "remote",
    "fashion",
    "romantic",
    "married",
    "escaped",
    "convict",
    "young",
    "possible",
    "male",
    "technological",
    "atomic",
    "only",
    "free",
]

snowClones = [
    "Do you like *adjective* *noun.s*?",
    "We all *verb* down here.",
    "Whatever you do, don't *verb*.",
    "I see *noun* people.",
    "We all go a little *adjective* sometimes.",
    "It's *noun*. It has a *noun*.",
    "You're gonna need a bigger *noun*.",
    "It's alive! It's *adjective* alive!",
    "No more *noun.s*. Ever.",
    "Whatever *verb.s* in the shadows, *verb.s* for *a.noun*.",
    "I am your worst *noun*.",
    "They mostly *verb* at night. Mostly.",
    "The power of *noun* compels you!",
    "We have such *noun.s* to show you.",
    "First rule: never *verb* the *noun*.",
    "You opened it. We came for the *noun*.",
    "This house is clean except for the *noun*.",
    "It's not the *noun* you should fear. It's the *noun* behind it.",
    "Trust me you don't want to *verb* the *noun*.",
    "May the *noun* be with you.",
    "You want the *repeatednoun*?! You can't HANDLE the *repeatednoun*!",
    "Show me the *noun*!",
    "Go ahead... make my *noun*.",
    "I'm gonna make him an offer he can't *verb*.",
    "Nobody puts *noun* in a corner.",
    "Life is like a box of *noun.s*.",
    "Say hello to my little *noun*!",
    "You had me at *noun*.",
    "I feel the need... the need for *noun*.",
    "There's no place like *noun*.",
    "Keep your friends close, but your *noun.s* closer.",
    "Houston, we have a *noun*.",
    "They may take our lives, but they'll never take our *noun.s*!",
    "I'll have what *noun* is having.",
    "Fasten your seatbelts, it's going to be a *adjective* *noun*.",
    "To infinity... and *noun*!",
    "I'm king of the *noun*!",
    "The first rule of *repeatednoun* Club is: you do not *verb* about *repeatednoun* Club.",
    "I love the smell of *noun* in the morning. Smells like... *noun*.",
    "The power of *repeatednoun* compels you! The power of *repeatednoun* compels you!",
    "*repeatednoun.s*? We don't need no stinking *repeatednoun.s*!",
    "*noun* means never having to say you're sorry.",
    "I'm just *a.noun*, standing in front of *a.noun*, asking it to love me.",
    "You make me want to be a better *noun*.",
    "It's *adjective*. It's *noun*. It's fate!",
    "I'm just looking for a *adjective* *noun* to share my life with.",
    "Don't marry the *repeatednoun* you can live with, marry the *repeatednoun* you can't live without",
    "You make me feel like I'm living in a *adjective* *noun*.",
    "To me, you are perfect... except for the *noun*.",
    "I guess when you know, you know... and I know it's *noun*.",
    "You are my greatest *noun* and my hardest *noun*.",
    "Sometimes the *noun* you're looking for is right in front of your *noun*.",
    "Resistance is *adjective*.",
    "To boldly go where no *noun* has gone before.",
    "The needs of the *noun.s* outweigh the needs of the *noun.s*.",
    "Don't, stop! *verb*, ing! Hold on to that *noun*.",
    "We will, we will *verb* you.",
    "Hey! I just met you, and this is *adjective*, but here's my *noun*, so *verb* me maybe.",
    "Take me down to the *adjective* city where the grass is *adjective* and the *noun.s* are pretty",
    "You are my *repeatednoun*, my only *repeatednoun*. You make me *verb* when skies are *adjective*",
    "Just a small-town *noun*, livin in a *adjective* *noun*. Took the midnight *noun* goin anywhere",
    "Straight outta *noun*, crazy *noun* named *name*.",
    "I got 99 *noun.s* but a *noun* ain't one.",
    "Cache rules everything around me, *noun* get the *noun*",
    "Started from the *noun*, now we're *noun*.",
    "Throw your *noun.s* in the air and wave 'em like you just don't *verb*.",
    "I got my mind on my *repeatednoun* and my *repeatednoun* on my mind.",
    "They see me *verb.ing*, they hatin'."

]


def a_or_an(word):
    return "an" if word[0].lower() in "aeiou" else "a"


def pluralize(noun):
    if noun.endswith("y") and noun[-2] not in "aeiou":
        return noun[:-1] + "ies"
    if noun.endswith(("s", "x", "z", "ch", "sh")):
        return noun + "es"
    return noun + "s"


def verb_s(verb):
    if verb.endswith("y") and verb[-2] not in "aeiou":
        return verb[:-1] + "ies"
    if verb.endswith(("s", "x", "z", "ch", "sh")):
        return verb + "es"
    return verb + "s"


def verb_ing(verb):
    if verb.endswith("e"):
        return verb[:-1] + "ing"
    return verb + "ing"


def fill_snowclone(template):
    output = template

    # Handle repeated noun first
    # Find any form of repeatednoun markers
    if re.search(r"\*a?\.?repeatednoun(?:\.s)?\*", output):
        # choose ONE noun to use for the whole template
        noun = random.choice(nouns)
        plural_noun = pluralize(noun)

        # replace *repeatednoun*
        output = output.replace("*repeatednoun*", noun)

        # replace *a.repeatednoun*
        article_noun = f"{a_or_an(noun)} {noun}"
        output = output.replace("*a.repeatednoun*", article_noun)

        # plural replacements
        output = output.replace("*repeatednoun.s*", plural_noun)
        # output = output.replace("*a.repeatednoun.s*", f"{a_or_an(plural_noun)} {plural_noun}")

    # *a.noun*
    for match in re.findall(r"\*a\.noun\*", output):
        n = random.choice(nouns)
        output = output.replace(match, f"{a_or_an(n)} {n}", 1)

    # *a.adjective*
    for match in re.findall(r"\*a\.adjective\*", output):
        adj = random.choice(adjectives)
        output = output.replace(match, f"{a_or_an(adj)} {adj}", 1)

    # plural nouns *noun.s*
    for match in re.findall(r"\*noun\.s\*", output):
        n = pluralize(random.choice(nouns))
        output = output.replace(match, n, 1)

    # plural adjectives? (not used, but you had the pattern)
    for match in re.findall(r"\*adjective\.s\*", output):
        adj = random.choice(adjectives) + "s"
        output = output.replace(match, adj, 1)

    # verb.s → 3rd-person singular
    for match in re.findall(r"\*verb\.s\*", output):
        v = verb_s(random.choice(verbs))
        output = output.replace(match, v, 1)

    # *verb*ing (gerund)
    for match in re.findall(r"\*verb\*ing", output):
        v = verb_ing(random.choice(verbs))
        output = output.replace(match, v, 1)

    # *verb*ed (past tense — naive)
    for match in re.findall(r"\*verb\*ed", output):
        v = random.choice(verbs) + "ed"
        output = output.replace(match, v, 1)

    # *verb*
    for match in re.findall(r"\*verb\*", output):
        v = random.choice(verbs)
        output = output.replace(match, v, 1)

    # *adjective*
    for match in re.findall(r"\*adjective\*", output):
        a = random.choice(adjectives)
        output = output.replace(match, a, 1)

    # *noun*
    for match in re.findall(r"\*noun\*", output):
        n = random.choice(nouns)
        output = output.replace(match, n, 1)

    # *name*
    for match in re.findall(r"\*name\*", output):
        n = random.choice(names)
        output = output.replace(match, n, 1)

    return output


def get_random_snowclone():
    template = random.choice(snowClones)
    return fill_snowclone(template)


def getText(captions):
    firstHalfArray = []
    secondHalfArray = []
    for i in range(10):  # try at max 10 times
        # Pick random captions and split into words
        firstHalfArray = random.choice(captions).split(" ")
        # Keep roughly half from firstHalfArray
        start_index = int(
            random.random() * len(firstHalfArray) * 0.5
            + random.random() * len(firstHalfArray) * 0.5
        )
        firstHalfArray = firstHalfArray[0:start_index]
        if len(firstHalfArray) > 1:
            break
    for i in range(10):  # try at max 10 times
        secondHalfArray = random.choice(captions).split(" ")
        # Remove roughly half from the start of secondHalfArray
        start_index = int(
            random.random() * len(secondHalfArray) * 0.5
            + random.random() * len(secondHalfArray) * 0.5
        )
        secondHalfArray = secondHalfArray[start_index:]
        if len(secondHalfArray) > 1:
            break
    # Combine arrays into a single string
    result = " ".join(firstHalfArray + secondHalfArray)
    if random.random() < 0.001 or len(result) < 3:
        return random.choice(captions)
    return result


for i in range(100):
    print(get_random_snowclone())
