IRREGULAR_VERBS = {
    "allow":"allowed",
    "be": "was",
    "become": "became",
    "bring": "brought",
    "build": "built",
    "come": "came",
    "deal": "dealt",
    "destroy":"destroyed",
    "draw": "drew",
    "dream": "dreamt",
    "drive": "drove",
    "dwell": "dwelt",
    "fall": "fell",
    "feel": "felt",
    "find": "found",
    "freeze": "froze",
    "get": "got",
    "give": "gave",
    "go": "went",
    "have": "had",
    "hear": "heard",
    "hide": "hid",
    "hurt": "hurt",
    "know": "knew",
    "learn": "learnt",
    "leave": "left",
    "make": "made",
    "meet": "met",
    "plead": "pled",
    "put": "put",
    "run": "ran",
    "say": "said",
    "see": "saw",
    "send": "sent",
    "set": "set",
    "speak": "spoke",
    "take": "took",
    "tear": "tore",
    "think": "thought",
    "win": "won"
}