NAMES = [
    "Nyah",
    "Devil Girl",
    "Vincent Price",
    "Peter Cushing",
    "Wrong Frog",
    "Space Master",
    "Space Freak",
    "Swamp Thing",
    "Space Monster",
    "Cat Girl",
    "Star Creature",
    "Bee Girl",
    "Giant Spider",
    "Aztec Mummy",
    "Monolith Monster",
    "Blacula",
    "Nosferatu",
    "Count Dracula",
    "Godzilla",
    "Body Snatcher",
    "Wicker Man",
    "Vincent Price",
    "Peter Cushing",
    "Devil Girl",
    "Wrong Frog",
    "Frankenstein"
]