NAMES = [
    "Nyah",
    "Devil Girl",
    "Vincent Price",
    "Peter Cushing",
    "Christopher Lee",
    "Bela Lugosi",
    "Roger Corman",
    "Ray Harryhausen",
    "Stephen King",
    "Wes Craven",
    "Lon Chaney Jr.",
    "Boris Karloff",
    "Bruce Campbell",
    "Satan",
    "Gojira",
    "Wrong Frog",
    "Space Master",
    "Space Freak",
    "Swamp Thing",
    "Space Monster",
    "Cat Girl",
    "Star Creature",
    "Bee Girl",
    "Giant Spider",
    "Aztec Mummy",
    "Monolith Monster",
    "Blacula",
    "Nosferatu",
    "Count Dracula",
    "Godzilla",
    "Body Snatcher",
    "Wicker Man",
    "Vincent Price",
    "Peter Cushing",
    "Devil Girl",
    "Wrong Frog",
    "Frankenstein",
    "Grizzly",
    "Gorgon",
    "Asphyx",
    "Pumpkinhead",
    "Godmonster",
    "Mothra",
    "Matango",
    "Megalon",
    "Gamera",
    "Mechagodzilla",
    "King Ghidorah",
    "Destoroyah",
    "King Kong",
    "Rodan",
    "Baragon",
    "He-Man",
    "Skeletor",
    "Gwildor",

]