NOUNS = [
    "achievement",
    "affair",
    "airliner",
    "alias",
    "Alligator",
    "area",
    "Asphyx",
    "astrophysicist",
    "Atlantis",
    "atmosphere",
    "Attack",
    "Aztec",
    "bar",
    "bargain",
    "barmaid",
    "bat",
    "Battle",
    "Beach",
    "beam",
    "Bechdel test",
    "Bikini",
    "birth",
    "Blood",
    "Bog",
    "bomb",
    "brain",
    "C.H.U.D.",
    "Cat",
    "chain",
    "characteristic",
    "Chekhov's gun",
    "Circus",
    "civilization",
    "Clash",
    "commander",
    "condensity",
    "control",
    "controller",
    "convict",
    "council",
    "course",
    "craft",
    "crash",
    "Creature",
    "Critter",
    "cross",
    "Crystal",
    "Curse",
    "damage",
    "decline",
    "defense",
    "Devil",
    "dimension",
    "double",
    "Dracula",
    "dream",
    "drink",
    "drive",
    "Earth",
    "Earthman",
    "effect",
    "effort",
    "emancipation",
    "emotion",
    "encounter",
    "exchange",
    "explosion",
    "Eye",
    "fear",
    "fission",
    "Food",
    "fool",
    "Forbidden",
    "force",
    "fragment",
    "Frankenstein",
    "Freak",
    "friction",
    "Fright",
    "Frog",
    "G8",
    "gain",
    "Gate",
    "Ghidorah",
    "Giant",
    "Girl",
    "God",
    "Godzilla",
    "Gorgon",
    "government",
    "Grizzly",
    "ground",
    "guest",
    "Gun",
    "Hennessey",
    "Highlands",
    "Horror",
    "hour",
    "house",
    "Howling",
    "human",
    "Hunger",
    "inn",
    "intelligence",
    "Invasion",
    "invention",
    "journalist",
    "King",
    "Krull",
    "Lagoon",
    "landing",
    "Laserblast",
    "Legend",
    "liaison",
    "life",
    "Little",
    "London",
    "lot",
    "Magic",
    "mail",
    "male",
    "Man",
    "manner",
    "manor",
    "Mars",
    "Master",
    "Mastodon",
    "matter",
    "mechanism",
    "metal",
    "meteorite",
    "millennium",
    "mind",
    "model",
    "molecular",
    "Monster",
    "Monsterdon",
    "Moon",
    "moor",
    "Mothra",
    "motion",
    "Mummy",
    "Mutation",
    "Mutoid",
    "nephew",
    "Night",
    "nuclear",
    "Nyah",
    "Overdrive",
    "pair",
    "Part",
    "part",
    "people",  # Retaining 'people' as a singular collective noun
    "Phantom",
    "Piranha",
    "plan",
    "planet",
    "population",
    "power",
    "Prisoner",
    "Professor",
    "Pumpkinhead",
    "Puppet",
    "radio",
    "rate",
    "Raven",
    "ray",
    "raygun",
    "reactor",
    "receptionist",
    "repair",
    "result",
    "Return",
    "Revenge",
    "riddle",
    "road",
    "Robot",
    "room",
    "ruler",
    "sabotage",
    "Samurai",
    "saucer",
    "savage",
    "science",
    "scientist",
    "Scottish Highland",
    "second",
    "sex",
    "ship",
    "Shop",
    "Slug",
    "Snowbeast",
    "source",
    "Space",
    "spaceship",
    "spare",
    "specimen",
    "Spider",
    "staff",
    "Star",
    "Starcrash",
    "structure",
    "subject",
    "Summit",
    "survivor",
    "Swamp",
    "Sword",
    "take",
    "team",
    "television",
    "Thing",
    "time",
    "Titan",  # Singularized 'Titans'
    "toy",
    "trick",
    "trickery",
    "triumph",
    "Truck",
    "Universe",
    "universe",
    "Vampire",
    "Victory",
    "victory",
    "view",
    "volunteer",  # Singularized 'volunteers'
    "wall",
    "war",
    "way",
    "weapon",
    "wife",
    "Wing",
    "woman",  # Singularized 'women'
    "wonder",
    "world",
    "X-7",
    "year",
    "Yeti",
    # Compound Nouns (Treated as Singular Proper Nouns)
    "Vampire Doll",
    "Puppet Person",  # Singularized
    "Outer Space",
    "Space Master",
    "Bikini Beach",
    "Fright Night",
    "Red Planet",
    "Black Lagoon",
    "Space Freak",
    "Planet Mutoid",
    "Planet X",
    "Swamp Thing",
    "Little Shop",
    "Vampire Circus",
    "X-Ray Eye",
    "Space Monster",
    "Forbidden Planet",
    "Bat Person",  # Singularized
    "Cat Girl",
    "Star Creature",
    "Bee Girl",
    "Stepford Wife",  # Singularized
    "Giant Spider",
    "Aztec Mummy",
    "Phantom Planet",
    "Cat Woman",  # Singularized
    "Wrestling Woman",  # Singularized
    "Monolith Monster",
    "Blacula",
    "Nosferatu",
    "Count Dracula",
    "Godzilla",
    "Body Snatcher",
    "Wicker Man",
    "Vincent Price",
    "Peter Cushing",
    "Devil Girl",
    "Wrong Frog",
    "Food of the Gods",
    "Little Shop of Horror",
    "missile",
    "invader",
    "Mysterious Island",
    "comet",
    "Twins of Evil",
    "tentacle",
    "Megalon",
    "Gamera",
    "Mechagodzilla",
    "gargoyle",
    "Atom Brain",
    "stranger",
    "Venus",
    "kingdom",
    "Moon Base",
    "Godmonster",
    "Mothra",
    "Matango",
    "Killer Klown",
    "blob",
    "living dead",
    "King Ghidorah",
    "Destoroyah",
    "King Kong",
    "Rodan",
    "Baragon",
    "She-Creature",
]
