PLACES = [
    "Mars",
    "Earth",
    "Outer Space",
    "Bikini Beach",
    "Atlantis",
    "Bog",
    "Black Lagoon",
    "Phantom Planet",
    "Scottish Highlands",
    "Scottish moors",
    "Angry Red Planet",
    "Forbidden Planet",
    "Little Shop of Horrors",
    "Mysterious Island",
    "Venus",
    "Moon Base",
    "London",
    "G8 Summit",
    "Planet Mutoid",
    "Planet X",
    "Krull",
    "Eternia",
    "Kingdom of the Spiders",
    "Center of the Earth",
    "Washington",
    "Indian Flats",
    "Hell",
    "Planet of the Vampires",
    "Tokyo",
]