SNOWCLONES = [
    "going to *verb* like I've never *verb*ed before",
    "the only good *noun* is *a.adjective* *noun*",
    "whatever *verb.s* your *noun*",
    "my *noun* runneth over",
    "got *noun*?",
    "if *noun* is wrong, I don't want to be right",
    "Im in ur *noun* *verb*ing ur *noun*",
    "yes Virginia, there is *a.noun*",
    "not the *adjective*-est *noun* in the *noun*",
    "a few *noun*s short of a *noun*",
    "that's not *a.repeatednoun*. THIS is *a.repeatednoun*",
    "don't hate me because I'm *adjective*",
    "to *verb* or not to *verb*",
    "*noun*-core",
    "the *noun*-gate scandal",
    "I'm not *a.noun*, but I play one on TV",
    "I am *noun*, hear me *verb*",
    "Dammit Jim, I'm *a.noun*, not *a.noun*",
    "we don't need no stinkin' *noun.s*",
    "have *noun* will travel",
    "save an *a.noun*, ride *a.noun*",
    "in space, no one can hear you *verb*",
    "*noun* is the new *noun*",
    "I for one welcome our *noun.s* overlords",
    "*noun.s* and *noun.s* and *noun.s*, oh my!",
    "take this *noun* and shove it",
    "when I say *noun*, what I really mean is *noun*",
    "What Would *noun* Do?",
    "we're gonna need a bigger *noun*",
    "*noun* is hard, let's go shopping",
    "these are not the *noun.s* you're looking for",
    "there's no crying in X!",
    "*noun* 2: *adjective* Boogaloo",
    "my kingdom for *a.noun*",
    "I <3 *adjective* *noun*",
    "this is your brain on *noun*",
    "I *verb*, therefore I am",
    "all your *noun* are belong to us",
    "it's *noun.s* all the way down",
    "Love in the time of *noun*",
    "I can has *noun*?",
    "One does not simply *verb* into *noun*.",
    "Keep calm and *verb* *a.noun*.",
    "Not sure if *noun*... or *noun*.",
    "*verb* me like one of your *noun.s*.",
    "I have the *adjective* ground, *name*!",
    "You either die a *noun*, or live long enough to become the *noun*.",
    "A wild *noun* appeared!",
    "It's dangerous to go alone. Take this *noun*.",
    "Do not cite the ancient *noun.s* to me.",
    "I put the *noun* in *noun*.",
    "I showed you my *noun*, please respond.",
    "Behold, a man with *a.noun*.",
    "Local *noun* ruins everything.",
    "This is fine. This is *noun*.",
    "Press F to pay respects to *noun*.",
    "Guess I'll *verb*.",
    "Thanks, I hate *noun*.",
    "This ain't your grandma's *noun*.",
    "Keep your friends close and your *noun.s* closer.",
    "Live, laugh, *noun*.",
    "May the *noun* be with you.",
    "The cake is a *noun*.",
    "I used to be an adventurer like you, then I took *a.noun* to the knee.",
    "You had one job: protect the *noun*.",
    "Welcome to my TED talk on *noun*.",
    "Not all heroes wear capes; some carry *noun.s*.",
    "This is the way of the *noun*.",
    "Stronger than *noun*, faster than *noun*, powered by *noun*.",
    "It's over, *noun*! I have the *adjective* ground!",
    "Shut up and take my *noun*!",
    "I fear no *noun*, but that thing... it scares me.",
    "You can't spell *noun* without *noun*.",
    "Ah yes, my favorite hobby: *verb*ing *noun.s*.",
    "Every day we stray further from *noun*.",
    "Nobody: Absolutely nobody: *noun* *verb*",
    "Big *noun* energy.",
    "The prophecy foretold of *a.noun*.",
    "Is this *a.noun*?",
    "Congratulations! Your *noun* evolved into *noun*!",
    "Time is an illusion. *noun* doubly so.",
    "*noun* used *verb*. It's SUPER *adjective*!",
    "My disappointment is *adjective* and my *noun* is ruined",
    "Do you like *adjective* *noun.s*?",
    "We all *verb* down here.",
    "Whatever you do, don't *verb*.",
    "I see *noun* people.",
    "We all go a little *adjective* sometimes.",
    "It's *noun*. It has a *noun*.",
    "You're gonna need a bigger *noun*.",
    "It's alive! It's *adjective* alive!",
    "No more *noun.s*. Ever.",
    "Whatever *verb.s* in the shadows, *verb.s* for *a.noun*.",
    "I am your worst *noun*.",
    "They mostly *verb* at night. Mostly.",
    "The power of *noun* compels you!",
    "We have such *noun.s* to show you.",
    "First rule: never *verb* the *noun*.",
    "You opened it. We came for the *noun*.",
    "This house is clean except for the *noun*.",
    "It's not the *noun* you should fear. It's the *noun* behind it.",
    "Trust me you don't want to *verb* the *noun*.",
    "May the *noun* be with you.",
    "You want the *repeatednoun*?! You can't HANDLE the *repeatednoun*!",
    "Show me the *noun*!",
    "Go ahead... make my *noun*.",
    "I'm gonna make him an offer he can't *verb*.",
    "Nobody puts *noun* in a corner.",
    "Life is like a box of *noun.s*.",
    "Say hello to my little *noun*!",
    "You had me at *noun*.",
    "I feel the need... the need for *noun*.",
    "There's no place like *noun*.",
    "Keep your friends close, but your *noun.s* closer.",
    "Houston, we have a *noun*.",
    "They may take our lives, but they'll never take our *noun.s*!",
    "I'll have what *noun* is having.",
    "Fasten your seatbelts, it's going to be a *adjective* *noun*.",
    "To infinity... and *noun*!",
    "I'm king of the *noun*!",
    "The first rule of *repeatednoun* Club is: you do not *verb* about *repeatednoun* Club.",
    "I love the smell of *noun* in the morning. Smells like... *noun*.",
    "The power of *repeatednoun* compels you! The power of *repeatednoun* compels you!",
    "*repeatednoun.s*? We don't need no stinking *repeatednoun.s*!",
    "*noun* means never having to say you're sorry.",
    "I'm just *a.noun*, standing in front of *a.noun*, asking it to love me.",
    "You make me want to be a better *noun*.",
    "It's *adjective*. It's *noun*. It's fate!",
    "I'm just looking for a *adjective* *noun* to share my life with.",
    "Don't marry the *repeatednoun* you can live with, marry the *repeatednoun* you can't live without",
    "You make me feel like I'm living in a *adjective* *noun*.",
    "To me, you are perfect... except for the *noun*.",
    "I guess when you know, you know — and I know it's *noun*.",
    "You are my greatest *noun* and my hardest *noun*.",
    "Sometimes the *noun* you're looking for is right in front of your *noun*.",
    "Resistance is *adjective*.",
    "To boldly go where no *noun* has gone before.",
    "The needs of the *noun.s* outweigh the needs of the *noun.s*.",
    "Don't, stop! *verb*, ing! Hold on to that *noun*.",
    "We will, we will *verb* you.",
    "Hey! I just met you, and this is *adjective*, but here's my *noun*, so *verb* me maybe.",
    "Take me down to the *adjective* city where the grass is *adjective* and the *noun.s* are pretty",
    "You are my *repeatednoun*, my only *repeatednoun*. You make me *verb* when skies are *adjective*",
    "Just a small-town *noun*, livin in a *adjective* *noun*. Took the midnight *noun* goin anywhere",
    "Straight outta *noun*, crazy *noun* named *name*.",
    "I got 99 *noun.s* but a *noun* ain't one.",
    "Cache rules everything around me, *noun* get the *noun*",
    "Started from the *noun*, now we're *noun*.",
    "Throw your *noun.s* in the air and wave 'em like you just don't *verb*.",
    "I got my mind on my *repeatednoun* and my *repeatednoun* on my mind.",
    "They see me *verb.ing*, they hatin'.",
    "*name*, just *verb.ed* *a.noun*. Put *a.noun* against his head...",
    "Now we're *adjective*, and contagious, Here we are now, *verb* us.",
    "That's me in the *noun*. That's me in the spot! light! *verb.ing* my *noun*",
    "Because maybe, you're gonna be the *noun* that *verb.s* me.",
    "*verb* me *name* one more *noun*.",
    "Don't go *verb.ing* *noun.s*. Please stick to the *noun.s* and *noun.s* that you're used to.",
    "If you wannabe my *noun*, you gotta *verb* with my *noun.s*",
    "Some-BODY once *verb.ed* me the *noun* is gonna *verb* me",
    "I get *verb.ed* down, but I get *verb* again. You are never gonna *verb* me down."
    "*repeatedverb* me why-ee! Ain't nothing but *a.noun*. *repeatedverb* me why-ee! Ain't nothing but *a.noun*.",
    "Ain't nothin' but *a.noun* thang, baby! Two *adjective* *noun.s* goin' crazy",
    "I'm gonna *verb* 'em off. A seven *noun* army can't hold me back.",
    "You only get one *noun*. Do not *verb* your chance to *verb*.",
    "He was *a.adjective* *repeatednoun*. She said, 'See you later, *repeatednoun*.'",
    "Say it ain't so, I will not *verb*, *verb* the *noun.s* off, *verb* me *noun*",
    "Tell me you *repeatedverb* without telling me you *repeatedverb*.",
    "Have you tried turning it *adjective* and then back *adjective* again?",
    "That's *a.repeatednoun*. That's *a.repeatednoun* who *verb.s* on a *noun*.",
    "You wouldn't steal *a.noun*. You wouldn't download *a.noun*. You wouldn't *verb* *a.noun*",
    "The *adjective* is strong with this *noun*.",
    "What is *adjective* may never *verb*.",
    "Be careful who you call *adjective* in *noun*.",
    "I volunteer as *repeatednoun*! I volunteer as repeatednoun for *noun*.",
    "Who is this *noun* and why do they keep *verb.ing* the *noun*?",
    "It's like looking for *a.noun* in *a.noun*.",
    "That's a bold strategy, *name*. Let's see if it pays off for them",
    "It's an older *noun*, but it checks out",
    "I don't need *repeatednoun*. *repeatednoun* needs me.",
    "How do you do, fellow *noun.s*?",
    "Me: mom can we get *repeatednoun*? Mom: we have *repeatednoun* at home. The *repeatednoun* at home:",
    "Did you ever hear the tragedy of *name* the *adjective*?",
    "NSF*repeatednoun*: Not safe for *repeatednoun*",
    "I reject your *noun* and substitute my *noun*.",
    "It's just *a.noun*. What could possibly go *adjective*?",
    "I have come here to *verb* *repeatednoun* and *verb* *noun*, and I'm all out of *repeatednoun*",
    "We need to remember what's important in life: *noun.s*, *noun.s*, *repeatednoun*. Or *noun.s*, *noun.s*, *repeatednoun*. Doesn't matter, but *repeatednoun* is third",
    "A large *noun* the size of a small *noun*.",
    "What's heavier? A kilogram of *noun.s* or a kilogram of *noun.s*?",
    "I mean, it's one *noun*, *name*. What could it cost? 10 dollars?",
    "When you play the Game Of *noun.s*, you *verb* or you *verb*. There is no *adjective* *noun*.",
    "*verb* my *adjective* metal *noun*!",
    "This is the *adjective* *noun*. Everything is *adjective* all the time.",
]