SNOWCLONES = [
    "going to *verb* like I've never *verb*ed before",
    "the only good *noun* is *adjective.a* *noun*",
    "whatever *verb.s* your *noun*",
    "if *noun* is wrong, I don't want to *verb* right",
    "Im in ur *noun* *verb*ing ur *noun*",
    "yes *name*, there is *noun.a*",
    "not the *adjective*-est *noun* in the *noun*",
    "a few *noun*s short of *noun.a*",
    "that's not *repeatednoun.a*. THIS is *repeatednoun.a*",
    "don't *verb* me because I'm *adjective*",
    "to *verb* or not to *verb*",
    "*noun*-core",
    "the *noun*-gate scandal",
    "I'm not *noun.a*, but I *verb* one on TV",
    "I am *noun*, hear me *verb*",
    "Dammit Jim, I'm *noun.a*, not *noun.a*",
    "save an *noun.a*, ride *noun.a*",
    "in *place*, no one can hear you *verb*",
    "*noun* is the new *noun*",
    "I for one welcome our *adjective* *noun.s* overlords",
    "*noun.s* and *noun.s* and *noun.s*, oh my!",
    "take this *noun* and *verb* it",
    "when I say *noun*, what I really mean is *noun*",
    "*noun* is *adjective*, let's go *verb.ing*",
    "these are not the *noun.s* you're *verb.ing* for",
    "my *noun* for *noun.a*",
    "I <3 *adjective* *noun*",
    "this is your *noun* on *noun*",
    "One does not simply *verb* into *place*.",
    "Keep calm and *verb* *noun.a*.",
    "Not sure if *noun*... or *noun*.",
    "*verb* me like one of your *noun.s*.",
    "I have the *adjective* ground, *name*!",
    "You either die *noun.a*, or live long enough to become the *noun*.",
    "It's dangerous to go alone. Take this *noun*.",
    "I put the *noun* in *noun*.",
    "Keep your *noun.s* close and your *noun.s* closer.",
    "Stronger than *noun*, faster than *noun*, powered by *noun*.",
    "It's over, *noun*! I have the *adjective* ground!",
    "I fear no *repeatednoun*, but that *repeatednoun*... it scares me.",
    "You can't spell *noun* without *noun*.",
    "Ah yes, my favorite hobby: *verb*ing *noun.s*.",
    "Every day we *verb* further from *noun*.",
    "Nobody: Absolutely nobody: *noun* *verb.s*",
    "Congratulations! Your *noun* evolved into *noun*!",
    "*noun* used *verb*. It's SUPER *adjective*!",
    "My disappointment is *adjective* and my *noun* is ruined",
    "Do you like *adjective* *noun.s*?",
    "It's *noun*. It has *noun.a*.",
    "You're gonna need a bigger *noun*",
    "Whatever *verb.s* in the shadows, *verb.s* for *noun.a*.",
    "They mostly *verb* at night. Mostly.",
    "The power of *repeatednoun* compels you! THE POWER OF *repeatednoun.upper* COMPELS YOU!",
    "First rule: never *verb* the *noun*.",
    "It's not the *noun* you should fear. It's the *noun* behind it.",
    "Trust me you don't want to *verb* the *noun*.",
    "You want the *repeatednoun*?! You can't HANDLE the *repeatednoun*!",
    "I'm gonna make him *noun.a* he can't *verb*.",
    "Nobody puts *noun* in *noun.a*.",
    "Life is like *noun.a* of *noun.s*. You never know what you're gonna *verb*",
    "Keep your *noun.s* close, but your *noun.s* closer.",
    "They may take our *noun.s*, but they'll never take our *noun.s*!",
    "I'll *verb* what *noun* is *verb.ing*.",
    "Fasten your seatbelts, it's going to be *adjective.a* *noun*.",
    "The first rule of *repeatednoun* Club is: you do not *verb* about *repeatednoun* Club.",
    "I love the smell of *noun* in the morning. Smells like... *noun*.",
    "The power of *repeatednoun* compels you! The power of *repeatednoun* compels you!",
    "*repeatednoun.s*? We don't need no stinking *repeatednoun.s*!",
    "I'm just *noun.a*, standing in front of *noun.a*, asking it to love me.",
    "It's *adjective*. It's *noun*. It's fate!",
    "I'm just looking for *adjective.a* *noun* to share my life with.",
    "Don't marry the *repeatednoun* you can live with, marry the *repeatednoun* you can't live without",
    "You make me feel like I'm living in *adjective.a* *noun*.",
    "To me, you are *adjective*... except for the *noun*.",
    "You are my greatest *noun* and my hardest *noun*.",
    "Sometimes the *noun* you're looking for is right in front of your *noun*.",
    "To boldly *verb* where no *noun* has gone before.",
    "The needs of the *noun.s* outweigh the needs of the *noun.s*.",

    "Don't, stop! *verb* -ing! Hold on to that *noun*.",
    "Hey! I just met you, and this is *adjective*, but here's my *noun*, so *verb* me maybe.",
    "Take me down to the *adjective* *place* where the grass is *adjective* and the *noun.s* are pretty",
    "You are my *repeatednoun*, my only *repeatednoun*. You make me *verb* when skies are *adjective*",
    "Just a small-town *noun*, livin in *adjective.a* *place*. Took the midnight *noun* goin anywhere",
    "Straight outt*noun.a*, crazy *noun* named *name*.",
    "I got 99 *noun.s* but *noun.a* ain't one.",
    "Cash rules everything around me, *noun* get the *noun*",
    "Started from the *noun*, now we're *noun*.",
    "Throw your *noun.s* in the air and wave 'em like you just don't *verb*.",
    "I got my mind on my *repeatednoun* and my *repeatednoun* on my mind.",
    "*name*, just *verb.ed* *noun.a*. Put *noun.a* against his head",
    "Now we're *adjective*, and contagious, Here we are now, *verb* us.",
    "That's me in the *noun*. That's me in the spot! light! *verb.ing* my *noun*",
    "Because maybe, you're gonna be the *noun* that *verb.s* me. And after all, you're my wonder*noun*",
    "*verb* me *name* one more *noun*.",
    "Don't go *verb.ing* *noun.s*. Please stick to the *noun.s* and *noun.s* that you're used to.",
    "If you wannabe my *noun*, you gotta *verb* with my *noun.s*",
    "Some-BODY once *verb.ed* me the *noun* is gonna *verb* me",
    "I get *verb.ed* down, but I get *verb* again. You are never gonna *verb* me down."
    "*repeatedverb* me why-ee! Ain't nothing but *noun.a*. *repeatedverb* me why-ee! Ain't nothing but *noun.a*.",
    "Ain't nothin' but *noun.a* thang, baby! Two *adjective* *noun.s* goin' crazy",
    "I'm gonna *verb* 'em off. A seven *noun* army can't *verb* me back.",
    "You only get one *noun*. Do not *verb* your chance to *verb*.",
    "He was *adjective.a* *repeatednoun*. She said, 'See you later, *repeatednoun*.'",
    "Say it ain't so, I will not *verb*, *verb* the *noun.s* off, *verb* me *noun*",
    "If you *verb.ed* it then you should have put *noun.a* on it",
    "I *repeatedverb* I can *verb*. I *repeatedverb* I can *verb* the *noun*.",
    "Will the *adjective* *name* please *repeatedverb* up? Please *repeatedverb* up?",
    "Every *noun* you *verb*, every *noun* you *verb*. I'll be *verb.ing* you.",
    "*adjective* *noun.s* are *verb.ed* of this. Who am I to disagree?",
    "I will *verb*! Oh, as long as I know how to *verb*, I know I'll stay *adjective*.",
    "*verb* as you *verb*, as you *verb.ed*, as I want you to be.",
    "I don't want no *repeatednoun.s*. A *repeatednoun* is *noun.a* that can't *verb* no love from me",
    "Never gonna *verb* you up, never gonna *verb* you down. Never gonna *verb* around and *verb* you.",
    "*repeatedname*, *repeatedname*, *repeatedname*, *repeatedname*! I'm beggin' of you, please don't *verb* my *noun*",
    "People try to *verb* us d-down (talkin' bout my *repeatednoun*) Just because we *verb* around (talkin' bout my *repeatednoun*)",
    "Things they do look *adjective* c-c-cold (talkin' bout my *repeatednoun*) Hope I *verb* before I get old (talkin' bout my *repeatednoun*)",
    "I *verb* *a.adjective* *noun* of *noun.a*. *repeatedname*! *repeatedname*! Will you do the *noun*?",

    "Tell me you *repeatedverb* without telling me you *repeatedverb*.",
    "Have you tried turning it *adjective* and then back *adjective* again?",
    "That's *repeatednoun.a*. That's *repeatednoun.a* who *verb.s* on *noun.a*.",
    "You wouldn't steal *noun.a*. You wouldn't download *noun.a*. You wouldn't *verb* *noun.a*",
    "The *adjective* is strong with this *noun*.",
    "What is *adjective* may never *verb*.",
    "Be careful who you call *adjective* in *place*.",
    "I volunteer as *repeatednoun*! I volunteer as *repeatednoun* for *place*.",
    "Who is this *noun* and why do they keep *verb.ing* the *noun*?",
    "It's like looking for *noun.a* in *noun.a*.",
    "It's an older *noun*, sir, but it *verb.s* out",
    "I don't need *repeatednoun*. *repeatednoun* needs me.",
    "Me: mom can we get *repeatednoun*? Mom: we have *repeatednoun* at home. The *repeatednoun* at home:",
    "Did you ever hear the tragedy of *name* the *adjective*?",
    "NSF*repeatednoun*: Not safe for *repeatednoun*",
    "I reject your *noun* and substitute my *noun*.",
    "It's just *noun.a*. What could possibly go *adjective*?",
    "I have come here to *verb* *repeatednoun* and *verb* *noun*, and I'm all out of *repeatednoun*",
    "We need to remember what's important in life: *noun.s*, *noun.s*, *repeatednoun*. Or *noun.s*, *noun.s*, *repeatednoun*. Doesn't matter, but *repeatednoun* is third",
    "A large *noun* the size of a small *noun*.",
    "What's heavier? A kilogram of *noun.s* or a kilogram of *noun.s*?",
    "I mean, it's one *noun*, *name*. What could it cost? 10 dollars?",
    "When you play the Game Of *noun.s*, you *verb* or you *verb*. There is no *adjective* *noun*.",
    "*verb* my *adjective* metal *noun*!",
    "This is the *adjective* *noun*. Everything is *adjective* all the time.",
    "Teenage *adjective* *adjective* *repeatednoun.s*. Heroes in *adjective.a*-shell. *repeatednoun* power!"
]